##[>] 🤖🤖
version: 2

project_name: get-term-open-files-with

snapshot:
  version_template: '{{ envOrDefault "MODULE_VERSION" "0.0.0-local" }}'

before:
  hooks:
    - go mod tidy

builds:
  - id: get-term-open-files-with
    main: .
    binary: get-term-open-files-with
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: get-term-open-files-with
    formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  disable: true
##[<] 🤖🤖
