package render

// [>] 🤖🤖

import (
	"bytes"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/invopop/jsonschema"
)

func Compose(c Composition) ([]byte, error) {
	switch c.Opts.WriteType {
	case WriteTypeMergeUpsert:
		return mergeUpsertEnv(c.Existing, c.Body, c.Opts.MergeUpdate, c.Shell)
	case WriteTypePartial:
		if c.Opts.CommentPrefix == "" {
			return nil, fmt.Errorf("render %s: writeType partial requires commentPrefix", c.TmplName)
		}
		out, err := sectionsInject(string(c.Existing), string(StripMergeActions(c.Body)), c.Opts.CommentPrefix)
		if err != nil {
			return nil, fmt.Errorf("render %s onto %s: %w", c.TmplName, c.HeaderDest, err)
		}
		return []byte(out), nil
	}
	if c.Opts.CommentPrefix != "" {
		return nil, fmt.Errorf("render %s: commentPrefix needs writeType partial", c.TmplName)
	}
	var out bytes.Buffer
	if !c.Opts.SkipAutoGeneratedHeader {
		out.WriteString(autogenHeader(c.HeaderDest, c.TmplName))
		out.WriteByte('\n')
	}
	body := StripMergeActions(c.Body)
	if !c.Opts.RenderReferencedFiles {
		out.Write(body)
		return out.Bytes(), nil
	}

	inlined, err := resolveAtIncludes(c.RepoRoot, body)
	if err != nil {
		return nil, err
	}
	out.Write(inlined)
	return out.Bytes(), nil
}

func mergeUpsertEnv(existing, rendered []byte, mode string, shell func(string) (string, error)) ([]byte, error) {
	if mode == "" {
		mode = MergeUpdateNone
	}
	if !slices.Contains(MergeUpdateModes, mode) {
		return nil, fmt.Errorf("mergeUpsert: unknown mergeUpdate %q: want %s", mode, strings.Join(MergeUpdateModes, " | "))
	}
	merged := envLines(existing)
	renderedLines := envLines(rendered)
	for _, key := range slices.Sorted(maps.Keys(renderedLines)) {
		mark, bare := splitMergeAction(renderedLines[key])
		_, exists := merged[key]
		if !mergeWrites(mode, mark, exists) {
			continue
		}
		val, err := mergeValue(key, mark, bare, shell)
		if err != nil {
			return nil, err
		}
		merged[key] = val
	}
	var out bytes.Buffer
	for _, k := range slices.Sorted(maps.Keys(merged)) {
		fmt.Fprintf(&out, "%s=%s\n", k, merged[k])
	}
	return out.Bytes(), nil
}

func mergeWrites(mode string, mark mergeMark, exists bool) bool {
	if !exists {
		return true
	}
	switch mark.action {
	case MergeActionAlwaysUpdate:
		return true
	case MergeActionKeepIfExisting:
		return false
	}
	switch mode {
	case MergeUpdateAll:
		return true
	case MergeUpdateDependencies:
		return mark.action == MergeActionDependency
	case MergeUpdateShell:
		return mark.isShell()
	}
	return false
}

func mergeValue(key string, mark mergeMark, bare string, shell func(string) (string, error)) (string, error) {
	if mark.shellCmd == "" {
		return bare, nil
	}
	if shell == nil {
		return "", fmt.Errorf("mergeUpsert %s: deferred shell value with no runner", key)
	}
	out, err := shell(mark.shellCmd)
	if err != nil {
		return "", fmt.Errorf("mergeUpsert %s: %w", key, err)
	}
	return out, nil
}

func envLines(b []byte) map[string]string {
	lines := map[string]string{}
	for line := range strings.Lines(string(b)) {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, _ := strings.Cut(line, "=")
		lines[key] = val
	}
	return lines
}

func autogenHeader(out, tmplPath string) string {
	if strings.HasSuffix(out, ".md") {
		return fmt.Sprintf("<!-- autogenerated using %s -->", tmplPath)
	}
	return fmt.Sprintf("# autogenerated using %s", tmplPath)
}

func resolveAtIncludes(repoRoot string, body []byte) ([]byte, error) {
	var out bytes.Buffer
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if isAtIncludeLine(line) {
			content, err := os.ReadFile(atIncludePath(repoRoot, line))
			if err != nil {
				return nil, fmt.Errorf("@-include %q: %w", line, err)
			}
			out.Write(bytes.TrimRight(content, "\n"))
			out.WriteByte('\n')
			continue
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	return out.Bytes(), nil
}

func atIncludePath(repoRoot, line string) string {
	path := strings.TrimPrefix(line, "@")
	if rest, ok := strings.CutPrefix(path, "~/"); ok {
		path = "root/_home/" + rest
	}
	return filepath.Join(repoRoot, path)
}

// IncludePaths returns the resolved path of every @-include line in body.
func IncludePaths(repoRoot string, body []byte) []string {
	var paths []string
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if isAtIncludeLine(line) {
			paths = append(paths, atIncludePath(repoRoot, line))
		}
	}
	return paths
}

func UnresolvedIncludes(repoRoot string, body []byte) []string {
	missing := []string{}
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if !isAtIncludeLine(line) {
			continue
		}
		if _, err := os.Stat(atIncludePath(repoRoot, line)); err != nil {
			missing = append(missing, line)
		}
	}
	return missing
}

func isAtIncludeLine(line string) bool {
	if !strings.HasPrefix(line, "@") || len(line) < 2 {
		return false
	}
	return !strings.ContainsAny(line, " \t")
}

func (Options) JSONSchema() *jsonschema.Schema {
	s := &jsonschema.Schema{
		Description:          "per-dest render options",
		Type:                 "object",
		AdditionalProperties: jsonschema.FalseSchema,
		Properties:           jsonschema.NewProperties(),
	}
	s.Properties.Set("writeType", &jsonschema.Schema{
		Description: "how the rendered body lands: overwrite (default: header + body) | mergeUpsert (env KEY=VALUE union under the existing dest: a missing key is written, an existing key is kept unless mergeUpdate or a per-line mark says otherwise: `| alwaysUpdate` overwrites, `| keepIfExisting` keeps, `| dependency` tags a key for mergeUpdate dependencies, a `shell` value runs only when the key is written, and marking a multi-line block marks every KEY=VALUE line in it) | partial (each `[>] <name>` .. `[<] <name>` section of the rendered body replaces the same-named section of the existing dest, the rest of the dest untouched, no header; requires commentPrefix)",
		Enum:        []any{"", WriteTypeMergeUpsert, WriteTypePartial},
	})
	s.Properties.Set("mergeUpdate", &jsonschema.Schema{
		Description: "which existing keys a mergeUpsert dest overwrites: none (default: only missing keys) | dependencies (plus `| dependency` keys) | shell (plus shell-valued keys, their commands re-run) | all (every template key, dest-only keys kept); alwaysUpdate / keepIfExisting marks win in every mode; overridden by --merge-update / CHE_RENDER_TEMPLATES_MERGE_UPDATE",
		Enum:        []any{"", MergeUpdateNone, MergeUpdateDependencies, MergeUpdateShell, MergeUpdateAll},
	})
	s.Properties.Set("commentPrefix", &jsonschema.Schema{
		Description: "line-comment prefix the section markers sit behind under writeType partial (e.g. #, //, --, <!--); required with partial, rejected otherwise",
		Type:        "string",
	})
	s.Properties.Set("skipAutoGeneratedHeader", &jsonschema.Schema{
		Description: "drop the autogen header on the overwrite path (dests whose format forbids comments)",
		Type:        "boolean",
	})
	s.Properties.Set("renderReferencedFiles", &jsonschema.Schema{
		Description: "inline @-includes into the rendered body (overwrite path)",
		Type:        "boolean",
	})
	return s
}

//[<] 🤖🤖
