package render

// [>] 🤖🤖

import (
	"bytes"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/invopop/jsonschema"
)

func Compose(c Composition) ([]byte, error) {
	if c.Opts.WriteType == WriteTypeMergeUpsert {
		return mergeUpsertEnv(c.Existing, c.Body), nil
	}
	var out bytes.Buffer
	if !c.Opts.SkipAutoGeneratedHeader {
		out.WriteString(autogenHeader(c.HeaderDest, c.TmplName))
		out.WriteByte('\n')
	}
	if !c.Opts.RenderReferencedFiles {
		out.Write(c.Body)
		return out.Bytes(), nil
	}

	inlined, err := resolveAtIncludes(c.RepoRoot, c.Body)
	if err != nil {
		return nil, err
	}
	out.Write(inlined)
	return out.Bytes(), nil
}

func mergeUpsertEnv(existing, rendered []byte) []byte {
	merged := map[string]string{}
	readInto := func(b []byte) {
		for line := range strings.Lines(string(b)) {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			key, val, _ := strings.Cut(line, "=")
			merged[key] = val
		}
	}
	readInto(rendered)
	readInto(existing)
	var out bytes.Buffer
	for _, k := range slices.Sorted(maps.Keys(merged)) {
		fmt.Fprintf(&out, "%s=%s\n", k, merged[k])
	}
	return out.Bytes()
}

func autogenHeader(out, tmplPath string) string {
	if strings.HasSuffix(out, ".md") {
		return fmt.Sprintf("<!-- autogenerated using %s -->", tmplPath)
	}
	return fmt.Sprintf("# autogenerated using %s", tmplPath)
}

func resolveAtIncludes(repoRoot string, body []byte) ([]byte, error) {
	var out bytes.Buffer
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if isAtIncludeLine(line) {
			content, err := os.ReadFile(atIncludePath(repoRoot, line))
			if err != nil {
				return nil, fmt.Errorf("@-include %q: %w", line, err)
			}
			out.Write(bytes.TrimRight(content, "\n"))
			out.WriteByte('\n')
			continue
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	return out.Bytes(), nil
}

func atIncludePath(repoRoot, line string) string {
	path := strings.TrimPrefix(line, "@")
	if rest, ok := strings.CutPrefix(path, "~/"); ok {
		path = "root/_home/" + rest
	}
	return filepath.Join(repoRoot, path)
}

func UnresolvedIncludes(repoRoot string, body []byte) []string {
	missing := []string{}
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if !isAtIncludeLine(line) {
			continue
		}
		if _, err := os.Stat(atIncludePath(repoRoot, line)); err != nil {
			missing = append(missing, line)
		}
	}
	return missing
}

func isAtIncludeLine(line string) bool {
	if !strings.HasPrefix(line, "@") || len(line) < 2 {
		return false
	}
	return !strings.ContainsAny(line, " \t")
}

func (Options) JSONSchema() *jsonschema.Schema {
	s := &jsonschema.Schema{
		Description:          "per-dest render options",
		Type:                 "object",
		AdditionalProperties: jsonschema.FalseSchema,
		Properties:           jsonschema.NewProperties(),
	}
	s.Properties.Set("writeType", &jsonschema.Schema{
		Description: "how the rendered body lands: overwrite (default: header + body) | mergeUpsert (env KEY=VALUE union under the existing dest)",
		Enum:        []any{"", WriteTypeMergeUpsert},
	})
	s.Properties.Set("skipAutoGeneratedHeader", &jsonschema.Schema{
		Description: "drop the autogen header on the overwrite path (dests whose format forbids comments)",
		Type:        "boolean",
	})
	s.Properties.Set("renderReferencedFiles", &jsonschema.Schema{
		Description: "inline @-includes into the rendered body (overwrite path)",
		Type:        "boolean",
	})
	return s
}

//[<] 🤖🤖
