package render

// [>] 🤖🤖

type Options struct {
	WriteType               string `yaml:"writeType"`
	CommentPrefix           string `yaml:"commentPrefix"`
	SkipAutoGeneratedHeader bool   `yaml:"skipAutoGeneratedHeader"`
	RenderReferencedFiles   bool   `yaml:"renderReferencedFiles"`
}

const (
	WriteTypeMergeUpsert = "mergeUpsert"
	WriteTypePartial     = "partial"
)

// Data is the template root: .env (the profile's effective env) and .var (its variables).
type Data struct {
	Env map[string]string `json:"env"`
	Var map[string]string `json:"var"`
}

type Composition struct {
	Body       []byte
	Opts       Options
	HeaderDest string
	TmplName   string
	Existing   []byte
	RepoRoot   string
}

type remoteRef struct {
	repoURL string
	sshURL  string
	path    string
	gitRef  string
}

type groupNode struct {
	childRepos     []string
	childSubgroups []string
}

type treeNode map[string]treeNode

// [<] 🤖🤖
