package render

// [>] 🤖🤖

import (
	secretmanager "cloud.google.com/go/secretmanager/apiv1"
	onepassword "github.com/1password/onepassword-sdk-go"
)

type Options struct {
	WriteType               string `yaml:"writeType"`
	SkipAutoGeneratedHeader bool   `yaml:"skipAutoGeneratedHeader"`
	RenderReferencedFiles   bool   `yaml:"renderReferencedFiles"`
}

const WriteTypeMergeUpsert = "mergeUpsert"

type Composition struct {
	Body       []byte
	Opts       Options
	HeaderDest string
	TmplName   string
	Existing   []byte
	RepoRoot   string
}

type remoteRef struct {
	repoURL string
	sshURL  string
	path    string
	gitRef  string
}

type opBackend struct{ client *onepassword.Client }

type gcpBackend struct{ client *secretmanager.Client }

type groupNode struct {
	childRepos     []string
	childSubgroups []string
}

type treeNode map[string]treeNode

// [<] 🤖🤖
