package render

// TODO: consider redesigning the data model for these types now that they're consolidated in one place.

// [>] 🤖🤖

import (
	onepassword "github.com/1password/onepassword-sdk-go"
)

// Domain model:
//
//	Options      per-dest render options from che.yml (writeType,
//	             skipAutoGeneratedHeader, renderReferencedFiles)
//	Composition  one dest's inputs for Compose: rendered Body + Options +
//	             header/dest metadata + Existing content (mergeUpsert)

// Options: per-dest render options from che.yml, semantics in the JSONSchema
// fragment in render.go.
type Options struct {
	WriteType               string `yaml:"writeType"`
	SkipAutoGeneratedHeader bool   `yaml:"skipAutoGeneratedHeader"`
	RenderReferencedFiles   bool   `yaml:"renderReferencedFiles"`
}

// WriteTypeMergeUpsert: env KEY=VALUE union under the existing dest.
const WriteTypeMergeUpsert = "mergeUpsert"

// Composition is one dest's inputs for Compose.
type Composition struct {
	Body       []byte  // rendered template output (from Exec)
	Opts       Options // per-dest render options
	HeaderDest string  // dest path: picks header comment syntax (.md vs #)
	TmplName   string  // source name shown in the autogen header
	Existing   []byte  // current dest content (mergeUpsert only)
	RepoRoot   string  // base for @-include resolution
}

type remoteRef struct {
	repoURL string
	sshURL  string
	path    string
	gitRef  string
}

type sdkResolver struct{ client *onepassword.Client }

// groupNode: one subgroup dir's direct children. childRepos/childSubgroups are
// names (basenames) relative to this node's dir. Repos stop recursion (.git present).
type groupNode struct {
	childRepos     []string
	childSubgroups []string
}

type treeNode map[string]treeNode

// [<] 🤖🤖
