package render

// [>] 🤖🤖

import (
	"embed"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/konradodwrot/go-modules/che/internal/testutil"
	"gitlab.com/konradodwrot/go-modules/lib/testyml"
)

//go:embed all:testdata/spec all:testdata/fixture/split_frontmatter all:testdata/fixture/render_markdown
var td embed.FS

func TestHeader(t *testing.T) {
	testyml.Eq(t, td, "testdata/spec/header.test.spec.yml", func(t *testing.T, c testyml.Case[string]) (string, error) {
		return header(c.Input.Args.String(t, 0), "tmpl"), nil
	})
}

func TestResolveAtIncludes(t *testing.T) {
	dir := t.TempDir()
	testutil.WriteFile(t, filepath.Join(dir, "root/HOME/.config/agents/docs/comments.md"), "INCLUDED\n")
	got := string(resolveAtIncludes(dir, []byte("before\n@~/.config/agents/docs/comments.md\nafter\n")))
	assert.Contains(t, got, "INCLUDED")
	assert.Contains(t, got, "before")
	assert.Contains(t, got, "after")
	assert.NotContains(t, got, "@~", "at-include line must be replaced")
}

func TestIsAtInclude(t *testing.T) {
	testyml.Eq(t, td, "testdata/spec/is_at_include_line.test.spec.yml", func(t *testing.T, c testyml.Case[bool]) (bool, error) {
		return isAtIncludeLine(c.Input.Args.String(t, 0)), nil
	})
}

func TestComposeOverwrite(t *testing.T) {
	got := string(Compose(Composition{
		Body:       []byte("hello\n"),
		HeaderDest: "out.md",
		TmplName:   "t.ontoRepo.tpl",
	}))
	assert.Equal(t, "<!-- autogenerated using t.ontoRepo.tpl -->\nhello\n", got)
}

func TestComposeAtInclude(t *testing.T) {
	root := testutil.Tree(t, map[string]string{"inc.md": "INLINED\n"})
	got := string(Compose(Composition{
		Body:       []byte("@inc.md\n"),
		Opts:       Options{RenderReferencedFiles: true},
		HeaderDest: "AGENTS.md",
		TmplName:   "a.ontoRepo.tpl",
		RepoRoot:   root,
	}))
	assert.Contains(t, got, "INLINED")
	assert.NotContains(t, got, "@inc.md", "@-include must be inlined")
}

func TestComposeMergeUpsert(t *testing.T) {
	got := string(Compose(Composition{
		Body:     []byte("A=default\nB=default\n"),
		Opts:     Options{WriteType: WriteTypeMergeUpsert},
		Existing: []byte("B=kept\n"),
	}))
	assert.Equal(t, "A=default\nB=kept\n", got)
}

func TestComposeSkipAutoGeneratedHeader(t *testing.T) {
	body := "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----\n"
	got := string(Compose(Composition{
		Body:       []byte(body),
		Opts:       Options{SkipAutoGeneratedHeader: true},
		HeaderDest: "/home/ko/.ssh/id_access",
		TmplName:   "id_access.ontoHost.tpl",
	}))
	assert.Equal(t, body, got)
}

func TestComposeSkipHeaderWithAtInclude(t *testing.T) {
	root := testutil.Tree(t, map[string]string{"inc.md": "INLINED\n"})
	got := string(Compose(Composition{
		Body:       []byte("@inc.md\n"),
		Opts:       Options{SkipAutoGeneratedHeader: true, RenderReferencedFiles: true},
		HeaderDest: "AGENTS.md",
		TmplName:   "a.ontoRepo.tpl",
		RepoRoot:   root,
	}))
	assert.Equal(t, "INLINED\n", got)
}

func TestMergeUpsertEnv(t *testing.T) {
	rendered := []byte("A=default\nB=default\n# comment\n\n")
	existing := []byte("B=kept\nC=extra\n")
	assert.Equal(t, "A=default\nB=kept\nC=extra\n", string(mergeUpsertEnv(existing, rendered)))
}

func TestMergeUpsertEnvNoExisting(t *testing.T) {
	assert.Equal(t, "A=x\nB=y\n", string(mergeUpsertEnv(nil, []byte("B=y\nA=x\n"))))
}

// splitWant is split_frontmatter's expected.output: expected-file refs for the
// front and body halves.
type splitWant struct {
	FrontFile string `yaml:"frontFile"`
	BodyFile  string `yaml:"bodyFile"`
}

func TestSplitFrontmatter(t *testing.T) {
	testyml.Run(t, td, "testdata/spec/split_frontmatter.test.spec.yml", func(t *testing.T, c testyml.Case[splitWant]) {
		front, body := SplitFrontmatter(testyml.ReadFile(t, td, c.Input.Args.String(t, 0)))
		testyml.EqualExpected(t, td, c.Expected.Output.FrontFile, front)
		testyml.EqualExpected(t, td, c.Expected.Output.BodyFile, body)
	})
}

func TestReadBodyFrontmatter(t *testing.T) {
	root := testutil.Tree(t, map[string]string{"d.yml": "---\ntitle: T\n---\nk: v\n"})
	front, err := ReadFrontmatter(root, "d.yml")
	require.NoError(t, err)
	assert.Equal(t, "title: T\n", front)
	body, err := ReadBody(root, "d.yml")
	require.NoError(t, err)
	assert.Equal(t, "k: v\n", body)
}

func TestRenderMarkdown(t *testing.T) {
	testyml.Run(t, td, "testdata/spec/render_markdown.test.spec.yml", func(t *testing.T, c testyml.Case[struct{}]) {
		root := t.TempDir()
		testyml.CopyDir(t, td, c.Context.Pwd, root)
		got, err := RenderMarkdown(root, c.Input.Args.String(t, 0), c.Input.Args.Strings(t, 1)...)
		if c.Expected.Check(t, err) {
			return
		}
		testyml.EqualExpected(t, td, c.Expected.Files, got)
	})
}

func TestRenderMarkdownTildeAndCap(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	testutil.WriteFile(t, filepath.Join(home, "r.md"), "###### deep\n# top\n")
	got, err := RenderMarkdown("/unused", "~/r.md", "remove-frontmatter", "normalize-headings")
	require.NoError(t, err)
	assert.Equal(t, "###### deep\n## top", got, "6 stays 6, 1 -> 2")
}

func TestIsRateLimit(t *testing.T) {
	cases := map[error]bool{
		errors.New("performing a vault operation: rate limit exceeded"): true,
		errors.New("op resolve: secret not found"):                      false,
		nil: false,
	}
	for err, want := range cases {
		assert.Equal(t, want, isRateLimitErr(err), "isRateLimitErr(%v)", err)
	}
}

func TestRetry(t *testing.T) {
	rateLimit := errors.New("rate limit exceeded")
	delays := []time.Duration{1, 1, 1}

	t.Run("succeeds first try, no sleep", func(t *testing.T) {
		slept, calls := 0, 0
		v, err := retry(delays, func(time.Duration) { slept++ }, isRateLimitErr,
			func() (string, error) { calls++; return "ok", nil })
		require.NoError(t, err)
		assert.Equal(t, "ok", v)
		assert.Equal(t, 1, calls)
		assert.Equal(t, 0, slept)
	})

	t.Run("retries rate limit then succeeds", func(t *testing.T) {
		slept, calls := 0, 0
		v, err := retry(delays, func(time.Duration) { slept++ }, isRateLimitErr,
			func() (string, error) {
				calls++
				if calls < 3 {
					return "", rateLimit
				}
				return "ok", nil
			})
		require.NoError(t, err)
		assert.Equal(t, "ok", v)
		assert.Equal(t, 3, calls)
		assert.Equal(t, 2, slept)
	})

	t.Run("exhausts retries, returns last error", func(t *testing.T) {
		calls := 0
		_, err := retry(delays, func(time.Duration) {}, isRateLimitErr,
			func() (string, error) { calls++; return "", rateLimit })
		assert.ErrorIs(t, err, rateLimit)
		assert.Equal(t, len(delays)+1, calls)
	})

	t.Run("non-retryable error fails immediately", func(t *testing.T) {
		other := errors.New("bad ref")
		calls := 0
		_, err := retry(delays, func(time.Duration) {}, isRateLimitErr,
			func() (string, error) { calls++; return "", other })
		assert.ErrorIs(t, err, other)
		assert.Equal(t, 1, calls)
	})
}

func TestDirsTreeExpected(t *testing.T) {
	dir := testutil.Repo(t, map[string]string{"top": "x", ".hidden/file": "x", "docs/data/x": "x", "src/lib/y": "x"})
	got, err := DirsTree(dir)
	require.NoError(t, err)
	want, err := os.ReadFile("testdata/fixture/dirs-tree/expected.tree")
	require.NoError(t, err)
	assert.Equal(t, string(want), got)
}

func TestMakefileDoc(t *testing.T) {
	got, err := MakefileDoc("../cmd/render-makefile-doc/testdata/Makefile")
	require.NoError(t, err)
	want, err := os.ReadFile("../cmd/render-makefile-doc/testdata/expected.md")
	require.NoError(t, err)
	assert.Equal(t, string(want), got)
}

func TestDirsTreeMissing(t *testing.T) {
	_, err := DirsTree(t.TempDir())
	assert.Error(t, err, "outside a git repo")
}

func TestExecWithCtx(t *testing.T) {
	repoRoot := testutil.Repo(t, map[string]string{"x": "x"})
	body := "name: RO-{{ .repo }} rw: RW-{{ .repo }}"
	got, err := ExecWithCtx("t.tpl", []byte(body), repoRoot, map[string]string{"repo": "Notes"})
	require.NoError(t, err)
	assert.Equal(t, "name: RO-Notes rw: RW-Notes", string(got))
}

func TestExecWithCtxEmptyKeepsPlainExec(t *testing.T) {
	repoRoot := testutil.Repo(t, map[string]string{"x": "x"})
	got, err := ExecWithCtx("t.tpl", []byte("hello {{ \"world\" }}"), repoRoot, nil)
	require.NoError(t, err)
	assert.Equal(t, "hello world", string(got))
}

// [<] 🤖🤖
