package render

// [>] 🤖🤖

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	git "github.com/go-git/go-git/v5"
)

func TestHeader(t *testing.T) {
	if got := header("/x/y.md", "tmpl"); got != "<!-- autogenerated using tmpl -->" {
		t.Errorf("md header = %q", got)
	}
	if got := header("/x/config.toml", "tmpl"); got != "# autogenerated using tmpl" {
		t.Errorf("default header = %q", got)
	}
}

func TestResolveAtIncludes(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "root/HOME/.config/agents/docs/comments.md"), "INCLUDED\n")
	out := resolveAtIncludes(dir, []byte("before\n@~/.config/agents/docs/comments.md\nafter\n"))
	got := string(out)
	if !strings.Contains(got, "INCLUDED") || !strings.Contains(got, "before") || !strings.Contains(got, "after") {
		t.Errorf("at-include resolution = %q", got)
	}
	if strings.Contains(got, "@~") {
		t.Errorf("at-include line not replaced: %q", got)
	}
}

func TestIsAtInclude(t *testing.T) {
	cases := map[string]bool{
		"@~/.config/x":  true,
		"@path/to/file": true,
		"@ has space":   false,
		"text @middle":  false,
		"plain":         false,
		"@":             false,
	}
	for line, want := range cases {
		if got := isAtInclude(line); got != want {
			t.Errorf("isAtInclude(%q) = %v, want %v", line, got, want)
		}
	}
}

func TestComposeOverwrite(t *testing.T) {
	got := string(Compose(Composition{
		Body:       []byte("hello\n"),
		HeaderDest: "out.md",
		TmplName:   "t.ontoRepo.tpl",
	}))
	want := "<!-- autogenerated using t.ontoRepo.tpl -->\nhello\n"
	if got != want {
		t.Errorf("Compose overwrite = %q, want %q", got, want)
	}
}

func TestComposeAtInclude(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "inc.md"), "INLINED\n")
	got := string(Compose(Composition{
		Body:       []byte("@inc.md\n"),
		Opts:       Options{RenderReferencedFiles: true},
		HeaderDest: "AGENTS.md",
		TmplName:   "a.ontoRepo.tpl",
		RepoRoot:   root,
	}))
	if !strings.Contains(got, "INLINED") || strings.Contains(got, "@inc.md") {
		t.Errorf("Compose @-include not inlined: %q", got)
	}
}

func TestComposeMergeUpsert(t *testing.T) {
	got := string(Compose(Composition{
		Body:     []byte("A=default\nB=default\n"),
		Opts:     Options{WriteType: WriteTypeMergeUpsert},
		Existing: []byte("B=kept\n"),
	}))
	if got != "A=default\nB=kept\n" {
		t.Errorf("Compose mergeUpsert = %q", got)
	}
}

func TestComposeRaw(t *testing.T) {
	got := string(Compose(Composition{
		Body:       []byte("-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----\n"),
		Opts:       Options{WriteType: WriteTypeRaw},
		HeaderDest: "/home/ko/.ssh/id_access",
		TmplName:   "id_access.ontoHost.tpl",
	}))
	if got != "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----\n" {
		t.Errorf("Compose raw = %q", got)
	}
}

func TestMergeUpsertEnv(t *testing.T) {
	rendered := []byte("A=default\nB=default\n# comment\n\n")
	existing := []byte("B=kept\nC=extra\n")
	got := string(mergeUpsertEnv(existing, rendered))
	want := "A=default\nB=kept\nC=extra\n"
	if got != want {
		t.Errorf("mergeUpsertEnv = %q, want %q", got, want)
	}
}

func TestMergeUpsertEnvNoExisting(t *testing.T) {
	got := string(mergeUpsertEnv(nil, []byte("B=y\nA=x\n")))
	if got != "A=x\nB=y\n" {
		t.Errorf("mergeUpsertEnv defaults-only = %q", got)
	}
}

func TestSplitFrontmatter(t *testing.T) {
	front, body := SplitFrontmatter("---\ntitle: x\n---\nbody line\n")
	if front != "title: x\n" || body != "body line\n" {
		t.Errorf("split = %q / %q", front, body)
	}
	front, body = SplitFrontmatter("no frontmatter\n")
	if front != "" || body != "no frontmatter\n" {
		t.Errorf("no-frontmatter split = %q / %q", front, body)
	}
}

func TestReadBodyFrontmatter(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "d.yml"), "---\ntitle: T\n---\nk: v\n")
	front, err := ReadFrontmatter(root, "d.yml")
	if err != nil || front != "title: T\n" {
		t.Errorf("ReadFrontmatter = %q, err %v", front, err)
	}
	body, err := ReadBody(root, "d.yml")
	if err != nil || body != "k: v\n" {
		t.Errorf("ReadBody = %q, err %v", body, err)
	}
}

func TestRenderMarkdown(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "p.md"),
		"---\npaths:\n  - x\n---\n\n## Heading\n\n<!-- drop me -->\ntext\n")
	got, err := RenderMarkdown(root, "p.md", "remove-frontmatter", "strip-comments", "normalize-headings")
	if err != nil {
		t.Fatal(err)
	}
	want := "### Heading\n\ntext"
	if got != want {
		t.Errorf("RenderMarkdown = %q, want %q", got, want)
	}
	// frontmatter kept when the opt is omitted
	kept, _ := RenderMarkdown(root, "p.md", "strip-comments")
	if !strings.HasPrefix(kept, "---") {
		t.Errorf("frontmatter should be kept without remove-frontmatter: %q", kept)
	}
	// unknown opt errors
	if _, err := RenderMarkdown(root, "p.md", "bogus"); err == nil {
		t.Error("unknown opt should error")
	}
}

func TestRenderMarkdownTildeAndCap(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	writeFile(t, filepath.Join(home, "r.md"), "###### deep\n# top\n")
	got, err := RenderMarkdown("/unused", "~/r.md", "remove-frontmatter", "normalize-headings")
	if err != nil {
		t.Fatal(err)
	}
	if got != "###### deep\n## top" { // 6 stays 6, 1 -> 2
		t.Errorf("RenderMarkdown tilde/cap = %q", got)
	}
}

func TestIsRateLimit(t *testing.T) {
	cases := map[error]bool{
		errors.New("performing a vault operation: rate limit exceeded"): true,
		errors.New("op resolve: secret not found"):                      false,
		nil: false,
	}
	for err, want := range cases {
		if got := isRateLimit(err); got != want {
			t.Errorf("isRateLimit(%v) = %v, want %v", err, got, want)
		}
	}
}

func TestRetry(t *testing.T) {
	rateLimit := errors.New("rate limit exceeded")
	delays := []time.Duration{1, 1, 1}

	t.Run("succeeds first try, no sleep", func(t *testing.T) {
		slept := 0
		calls := 0
		v, err := retry(delays, func(time.Duration) { slept++ }, isRateLimit,
			func() (string, error) { calls++; return "ok", nil })
		if v != "ok" || err != nil || calls != 1 || slept != 0 {
			t.Errorf("v=%q err=%v calls=%d slept=%d", v, err, calls, slept)
		}
	})

	t.Run("retries rate limit then succeeds", func(t *testing.T) {
		slept := 0
		calls := 0
		v, err := retry(delays, func(time.Duration) { slept++ }, isRateLimit,
			func() (string, error) {
				calls++
				if calls < 3 {
					return "", rateLimit
				}
				return "ok", nil
			})
		if v != "ok" || err != nil || calls != 3 || slept != 2 {
			t.Errorf("v=%q err=%v calls=%d slept=%d", v, err, calls, slept)
		}
	})

	t.Run("exhausts retries, returns last error", func(t *testing.T) {
		calls := 0
		_, err := retry(delays, func(time.Duration) {}, isRateLimit,
			func() (string, error) { calls++; return "", rateLimit })
		if !errors.Is(err, rateLimit) || calls != len(delays)+1 {
			t.Errorf("err=%v calls=%d, want %d", err, calls, len(delays)+1)
		}
	})

	t.Run("non-retryable error fails immediately", func(t *testing.T) {
		other := errors.New("bad ref")
		calls := 0
		_, err := retry(delays, func(time.Duration) {}, isRateLimit,
			func() (string, error) { calls++; return "", other })
		if !errors.Is(err, other) || calls != 1 {
			t.Errorf("err=%v calls=%d, want 1", err, calls)
		}
	})
}

func TestDirsTreeExpected(t *testing.T) {
	dir := initRepo(t, []string{"top", ".hidden/file", "docs/data/x", "src/lib/y"})
	got, err := DirsTree(dir)
	if err != nil {
		t.Fatalf("DirsTree: %v", err)
	}
	want, err := os.ReadFile("testdata/dirs-tree/expected.tree")
	if err != nil {
		t.Fatalf("read expected: %v", err)
	}
	if got != string(want) {
		t.Errorf("output mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestDirsTreeMissing(t *testing.T) {
	if _, err := DirsTree(t.TempDir()); err == nil {
		t.Fatal("expected error outside a git repo")
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func initRepo(t *testing.T, files []string) string {
	t.Helper()
	dir := t.TempDir()
	repo, err := git.PlainInit(dir, false)
	if err != nil {
		t.Fatalf("init: %v", err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatalf("worktree: %v", err)
	}
	for _, f := range files {
		writeFile(t, filepath.Join(dir, f), "x")
		if _, err := wt.Add(f); err != nil {
			t.Fatalf("add %s: %v", f, err)
		}
	}
	return dir
}

// [<] 🤖🤖
