##[>] 🤖🤖
#[what] Monorepo Makefile: repo-wide targets, fans out to module Makefiles
SHELL := zsh
.SHELLFLAGS := -c
MODULES := che get-os-open-files-with get-term-open-files-with lib

COMMANDS := che-install generic-setup repo-prepare-deps render-docs test test-cover build vet lint install che-install-test create-tag publish publish-prerelease release-schemas publish-schema-prerelease publish-brew publish-apt vendor-packages-defs release-check release-snapshot

.PHONY: $(COMMANDS)

#[why] this checkout's build wins: an MR may change che's own rendering, so a release che from PATH
#   would render the wrong output. CI supplies it as warm-go's artifact, skipping a rebuild
BIN_CHE ?= $(if $(wildcard che/dist/che),che/dist/che,che)
GENERIC_FILES_TRACKED_PROFILES := generic/filesTracked,repo/filesTracked
GENERIC_FILES_UNTRACKED_PROFILES := generic/filesUntracked,repo/filesUntracked
-include shared/generic/make/generic.mk

##[>] Dev Environment [genai-include]
#[what] install the latest released che into ~/.local/bin, only when the one on PATH is older
che-install:
	@curl -fsSL https://konradodwrot.gitlab.io/go-modules/che-install.sh | sh -s -- --skip-if-present-is-newer

#[what] render the generic consumer payload (generic.mk, lefthook.yml, shared/generic/) at the pinned CENTRALIZED_ASSETS_GENERIC_REF
generic-setup:
	@$(BIN_CHE) render-templates --profiles=genericSetup

shared/generic/make/generic.mk: generic-setup

#[why] deps installs the toolchain only, never `install`: that builds each module's binaries into
#   GOPATH, an output rather than a prerequisite, so preparing an environment must not run it
#[what] install this repo's toolchain
repo-prepare-deps:
	@che run --profiles=devEnv
##[<] Dev Environment

##[>] Docs [genai-include]
#[what] generate che docs (docs/cli.md, che.schema.json, cli-usage.md) from the Go source
render-docs:
	@$(MAKE) -C che render-docs
##[<] Docs

##[>] Go [genai-include]
#[what] run all tests in every module
test:
	@for m in $(MODULES); do $(MAKE) -C $$m test || exit 1; done

#[what] run every module's tests with coverage, print each module's total percentage
test-cover:
	@for m in $(MODULES); do $(MAKE) -C $$m test-cover || exit 1; done

#[what] build every module's binaries into <module>/dist
build:
	@for m in $(MODULES); do $(MAKE) -C $$m build || exit 1; done

#[what] go vet every module
vet:
	@for m in $(MODULES); do $(MAKE) -C $$m vet || exit 1; done

#[what] golangci-lint every module
lint:
	@for m in $(MODULES); do $(MAKE) -C $$m lint || exit 1; done

#[what] install every module's binaries into $GOPATH/bin
install:
	@for m in $(MODULES); do $(MAKE) -C $$m install || exit 1; done
##[<] Go

##[>] Install Script [genai-include]
#[args] OLD NEW (default: the two newest che releases from the packages API)
#[what] run che/che-install.sh through every install/skip scenario against two published versions, into a throwaway dir
che-install-test:
	@ci/che-install-test.sh $(OLD) $(NEW)
##[<] Install Script

##[>] Release [genai-include]
#[what] create the MODULE release + dir-prefixed git tag from BRANCH at REF via glab
#[args] MODULE BRANCH REF DEFAULT_BRANCH
create-tag:
	@ci/create-tag.zsh $(MODULE) $(BRANCH) $(REF) $(DEFAULT_BRANCH)

#[what] tag pipeline: goreleaser snapshot build for $CI_COMMIT_TAG's module, upload to the generic package registry, link release assets
publish:
	@ci/publish.zsh

#[what] MR pipeline: upload DIST_DIR's che_$(MODULE_VERSION)_<os>_<arch> archives to the generic package registry as one per-MR prerelease
publish-prerelease:
	@ci/publish-prerelease.zsh $(DIST_DIR)

#[what] main pipeline: mint and publish a release for each schema whose generated bytes changed, writing both versions to SCHEMA_VERSIONS_ENV
#[args] REF CHE_MIN_VERSION SCHEMA_VERSIONS_ENV
release-schemas:
	@ci/release-schemas.zsh $(REF)

#[what] MR pipeline: upload every generated schema to the generic package registry as one per-MR prerelease
publish-schema-prerelease:
	@ci/publish-schema-prerelease.zsh

#[what] tag pipeline: render Formula/che.rb + Formula/che@<version>.rb for $CI_COMMIT_TAG's version, commit them to the homebrew tap repo via the GitLab commits API
publish-brew:
	@ci/publish-brew-formula.zsh

#[what] rebuild the signed apt repo tree into ./public-apt from every che .deb in the generic package registry
publish-apt:
	@ci/publish-apt.zsh

#[what] vendor the pinned che-packages catalog into che/internal/packages/builtin/data (CHE_PACKAGES_DIR=<path> vendors a local checkout instead)
vendor-packages-defs:
	@ci/vendor-packages-defs.zsh

#[what] validate every module's goreleaser configs
release-check:
	@for m in $(MODULES); do $(MAKE) -C $$m release-check || exit 1; done

#[what] local snapshot build of every module, no publish
release-snapshot:
	@for m in $(MODULES); do $(MAKE) -C $$m release-snapshot || exit 1; done
##[<] Release
##[<] 🤖🤖
