##[>] 🤖🤖
#[what] Monorepo Makefile: repo-wide targets, fans out to module Makefiles
SHELL := zsh
.SHELLFLAGS := -c
MODULES := che get-os-open-files-with get-term-open-files-with lib

WRAPPERS := repo-prepare-dev-env
COMMANDS := render-templates repo-render-env repo-prepare-deps render-docs repo-ci-prepare-hooks repo-ci-precommit-all test test-cover build vet lint install create-tag publish publish-prerelease release-schemas publish-schema-prerelease publish-brew publish-apt vendor-packages-defs release-check release-snapshot

.PHONY: $(WRAPPERS) $(COMMANDS)

##[>] Dev Environment [genai-include]
#[why] render precedes hooks: the docsgen pre-commit hook runs render-templates and fails on drift,
#   so a fresh clone whose generated files were never rendered would fail its first commit
#[why] deps installs the toolchain only, never `install`: that builds each module's binaries into
#   GOPATH, an output rather than a prerequisite, so preparing an environment must not run it
#[what] make a fresh clone a working checkout: generated docs, toolchain, git hooks
repo-prepare-dev-env: repo-render-env render-templates repo-prepare-deps repo-ci-prepare-hooks

#[what] install this repo's toolchain
repo-prepare-deps:
	@che run --profiles=devEnv
##[<] Dev Environment

##[>] Docs [genai-include]
#[why] ontoRepo only: claude-agents renders untracked .claude/ from prose-generated snippets absent in a clone
#[why] this checkout's build wins: an MR may change che's own rendering, so a release che from PATH
#   would render the wrong output. CI supplies it as warm-go's artifact, skipping a rebuild
#[why] PATH che is the fallback, building the last resort: a fresh clone (repo-prepare-dev-env)
#   should not need a go toolchain to render its docs
#[what] render *.ontoRepo.tpl onto the repo with this checkout's che build
render-templates:
	@che_bin=che/dist/che; \
	if [[ ! -x $$che_bin ]] che_bin=$$(command -v che || true); \
	if [[ -z $$che_bin ]] { $(MAKE) -C che build; che_bin=che/dist/che }; \
	$$che_bin render-templates --profiles ontoRepo

#[what] render .env.tpl to .env: upstream refs and CI variables via glab, secrets via op
repo-render-env:
	@CHE_ENV_UNSET=empty che render-templates --profiles=envSeed

#[what] generate che docs (docs/cli.md, che.schema.json, cli-usage.md) from the Go source
render-docs:
	@$(MAKE) -C che render-docs
##[<] Docs

##[>] CI [genai-include]
#[what] install lefthook git hooks
repo-ci-prepare-hooks:
	@lefthook install --force

#[what] run pre-commit hooks over all files
repo-ci-precommit-all: repo-ci-prepare-hooks
	@lefthook run pre-commit --all-files --force
##[<] CI

##[>] Go [genai-include]
#[what] run all tests in every module
test:
	@for m in $(MODULES); do $(MAKE) -C $$m test || exit 1; done

#[what] run every module's tests with coverage, print each module's total percentage
test-cover:
	@for m in $(MODULES); do $(MAKE) -C $$m test-cover || exit 1; done

#[what] build every module's binaries into <module>/dist
build:
	@for m in $(MODULES); do $(MAKE) -C $$m build || exit 1; done

#[what] go vet every module
vet:
	@for m in $(MODULES); do $(MAKE) -C $$m vet || exit 1; done

#[what] golangci-lint every module
lint:
	@for m in $(MODULES); do $(MAKE) -C $$m lint || exit 1; done

#[what] install every module's binaries into $GOPATH/bin
install:
	@for m in $(MODULES); do $(MAKE) -C $$m install || exit 1; done
##[<] Go

##[>] Release [genai-include]
#[what] create the MODULE release + dir-prefixed git tag from BRANCH at REF via glab
#[args] MODULE BRANCH REF DEFAULT_BRANCH
create-tag:
	@ci/create-tag.zsh $(MODULE) $(BRANCH) $(REF) $(DEFAULT_BRANCH)

#[what] tag pipeline: goreleaser snapshot build for $CI_COMMIT_TAG's module, upload to the generic package registry, link release assets
publish:
	@ci/publish.zsh

#[what] MR pipeline: upload DIST_DIR's che_$(MODULE_VERSION)_<os>_<arch> archives to the generic package registry as one per-MR prerelease
publish-prerelease:
	@ci/publish-prerelease.zsh $(DIST_DIR)

#[what] main pipeline: mint and publish a release for each schema whose generated bytes changed, writing both versions to SCHEMA_VERSIONS_ENV
#[args] REF CHE_MIN_VERSION SCHEMA_VERSIONS_ENV
release-schemas:
	@ci/release-schemas.zsh $(REF)

#[what] MR pipeline: upload both generated schemas to the generic package registry as one per-MR prerelease
publish-schema-prerelease:
	@ci/publish-schema-prerelease.zsh

#[what] tag pipeline: render Formula/che.rb + Formula/che@<version>.rb for $CI_COMMIT_TAG's version, commit them to the homebrew tap repo via the GitLab commits API
publish-brew:
	@ci/publish-brew-formula.zsh

#[what] rebuild the signed apt repo tree into ./public-apt from every che .deb in the generic package registry
publish-apt:
	@ci/publish-apt.zsh

#[what] vendor the pinned che-packages catalog into che/internal/packages/builtin/data (CHE_PACKAGES_DIR=<path> vendors a local checkout instead)
vendor-packages-defs:
	@ci/vendor-packages-defs.zsh

#[what] validate every module's goreleaser configs
release-check:
	@for m in $(MODULES); do $(MAKE) -C $$m release-check || exit 1; done

#[what] local snapshot build of every module, no publish
release-snapshot:
	@for m in $(MODULES); do $(MAKE) -C $$m release-snapshot || exit 1; done
##[<] Release
##[<] 🤖🤖
