##[>] 🤖🤖
version: 2

project_name: get-os-open-files-with

gitlab_urls:
  use_job_token: true

before:
  hooks:
    - go mod tidy

builds:
  - id: get-os-open-files-with
    main: .
    binary: get-os-open-files-with
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: get-os-open-files-with
    formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: git
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.*$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\(.+\))?!?:.*$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  gitlab:
    owner: konradodwrot/go
    name: get-os-open-files-with
##[<] 🤖🤖
