// Docgen renders che's reference docs from the Go source: che.schema.json, docs/cli.md, cli-usage.md.
package main

// [>] 🤖🤖

import (
	"cmp"
	"encoding/json"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"gitlab.com/konradodwrot/go-modules/che/internal/cli"
	"gitlab.com/konradodwrot/go-modules/che/internal/spec"
	"gitlab.com/konradodwrot/go-modules/che/internal/telemetry"
)

const (
	schemaPath           = "assets/data/che.schema.json"
	cliDocPath           = "docs/cli.md"
	cliUsagePath         = "assets/data/cli-usage.md"
	observabilityDocPath = "docs/observability.md"
)

func main() {
	must(os.MkdirAll("docs", 0o755))
	root := cli.New().Root()
	root.InitDefaultCompletionCmd()
	must(os.WriteFile(schemaPath, schemaJSON(), 0o644))
	must(os.WriteFile(cliDocPath, []byte(cliDoc(root)), 0o644))
	must(os.WriteFile(cliUsagePath, []byte(cliUsage(root)), 0o644))
	must(os.WriteFile(observabilityDocPath, []byte(observabilityDoc()), 0o644))
	for _, p := range []string{schemaPath, cliDocPath, cliUsagePath, observabilityDocPath} {
		fmt.Println("wrote", p)
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

// schemaJSON marshals spec.Schema() deterministically (properties in struct
// field order, $defs sorted, indented, trailing newline).
func schemaJSON() []byte {
	b, err := json.MarshalIndent(spec.Schema(), "", "  ")
	must(err)
	return append(b, '\n')
}

// splitSeg cuts a "; <key>: <val>" trailer off desc, returning the rest and val.
func splitSeg(desc, key string) (rest, val string) {
	rest, val, _ = strings.Cut(desc, key)
	return rest, val
}

func tick(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

// renderOptionsTable renders a FlagSet as an Option|Env|Values|Default|Description
// table. Each flag's usage string may carry "; values: <...>",
// "; default: <...>" and "; env: <...>" segments feeding those columns
// (values default: the flag's value type; default default: the flag's
// non-empty DefValue; flag wins over env).
func renderOptionsTable(fs *pflag.FlagSet) string {
	var b strings.Builder
	b.WriteString("| Option | Env | Values | Default | Description |\n| --- | --- | --- | --- | --- |\n")
	fs.VisitAll(func(f *pflag.Flag) {
		desc, env := splitSeg(f.Usage, "; env: ")
		desc, def := splitSeg(desc, "; default: ")
		desc, values := splitSeg(desc, "; values: ")
		env = tick(env)
		values = tick(strings.ReplaceAll(values, " | ", "` \\| `"))
		if values == "" {
			values = "`" + f.Value.Type() + "`"
		}
		def = tick(cmp.Or(def, f.DefValue))
		opt := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			opt = "`-" + f.Shorthand + "`, " + opt
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", opt, env, values, def, desc)
	})
	return b.String()
}

// cliDoc renders the CLI reference: root Long + the global options table,
// then every subcommand (depth-first, name-sorted) with its own table.
func cliDoc(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- autogenerated using internal/docgen -->\n")
	b.WriteString("# che CLI\n\n")
	b.WriteString(root.Long)
	b.WriteString("\n\n")
	b.WriteString("## Global options\n\n")
	b.WriteString(renderOptionsTable(root.PersistentFlags()))
	b.WriteString("\n## Commands\n")
	walkCommands(root, &b)
	return b.String()
}

// cliUsage renders the README usage listing: every command (subcommands
// indented) with its Short, then the global flags. Included by the README
// template via renderMarkdown.
func cliUsage(root *cobra.Command) string {
	var rows [][2]string
	var collect func(cmd *cobra.Command, indent string)
	collect = func(cmd *cobra.Command, indent string) {
		for _, sub := range sortedSubs(cmd) {
			rows = append(rows, [2]string{indent + sub.Name(), sub.Short})
			collect(sub, indent+"  ")
		}
	}
	collect(root, "  ")
	width := 0
	for _, r := range rows {
		width = max(width, len(r[0]))
	}
	var b strings.Builder
	b.WriteString("che [command]\n\nAvailable Commands:\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "%-*s  %s\n", width, r[0], r[1])
	}
	b.WriteString("\nFlags:\n")
	b.WriteString(root.PersistentFlags().FlagUsages())
	return b.String()
}

func sortedSubs(cmd *cobra.Command) []*cobra.Command {
	subs := slices.Clone(cmd.Commands())
	subs = slices.DeleteFunc(subs, func(c *cobra.Command) bool { return !c.IsAvailableCommand() })
	slices.SortFunc(subs, func(a, b *cobra.Command) int { return strings.Compare(a.Name(), b.Name()) })
	return subs
}

func walkCommands(cmd *cobra.Command, b *strings.Builder) {
	for _, sub := range sortedSubs(cmd) {
		fmt.Fprintf(b, "\n### `$ %s`\n\n%s.\n", sub.CommandPath(), strings.TrimSuffix(sub.Short, "."))
		if sub.Long != "" {
			fmt.Fprintf(b, "\n%s\n", sub.Long)
		}
		if use := strings.TrimSuffix(sub.UseLine(), " [flags]"); use != sub.CommandPath() {
			fmt.Fprintf(b, "\nUsage: `%s`\n", sub.UseLine())
		}
		if sub.NonInheritedFlags().HasAvailableFlags() {
			fmt.Fprintf(b, "\n%s", renderOptionsTable(sub.NonInheritedFlags()))
		}
		walkCommands(sub, b)
	}
}

// labelValue is one observed value of a metric label plus its one-line meaning.
type labelValue struct{ Value, Meaning string }

// labelValues is the hand-curated vocabulary of the che.* metric labels,
// sourced from the emission sites in internal/che (Operation.Name(),
// opInfo.kind, deriveOpType, run_scripts.go) and the CLI commands.
// Kept in sync by hand: these are observed values, not an enforced enum.
var labelValues = []struct {
	Label  string
	Values []labelValue
}{
	{"op", []labelValue{
		{"prune-broken-links", "remove ledger-recorded links whose source is gone"},
		{"make-dirs", "create repo-tree dirs + extra-dirs"},
		{"make-links", "symlink configs into the system root"},
		{"make-copies", "copy *.ontoHost.cp sources onto their dests"},
		{"render-templates", "render *.tpl sources onto repo/home/host"},
		{"run-scripts", "run the profile's scripts"},
	}},
	{"kind", []labelValue{
		{"link", "a symlink dest"},
		{"copy", "a copied file dest"},
		{"render", "a rendered template dest"},
		{"dir", "a created directory"},
		{"chmod", "a mode change"},
		{"chown", "an owner change"},
		{"rm", "a removed dest"},
		{"script", "a run-scripts script execution"},
	}},
	{"op_type", []labelValue{
		{"create", "dest went from absent to present"},
		{"remove", "dest went from present to absent"},
		{"update", "dest changed kind/target/mode in place"},
		{"noop", "dest already at the desired state"},
		{"ok", "script ran successfully (kind=script)"},
		{"fail", "script failed (kind=script)"},
	}},
	{"command", []labelValue{
		{"run", "the `run` full-install command"},
		{"uninstall", "the `uninstall` command"},
		{"discover", "the `discover` command"},
		{"prune-broken-links", "the `prune-broken-links` per-op command"},
		{"make-dirs", "the `make-dirs` per-op command"},
		{"make-links", "the `make-links` per-op command"},
		{"make-copies", "the `make-copies` per-op command"},
		{"render-templates", "the `render-templates` per-op command"},
		{"run-scripts", "the `run-scripts` per-op command"},
	}},
}

// observabilityDoc renders the telemetry reference from the telemetry.Metrics
// registry (metric table) and the curated labelValues (per-label vocabularies),
// plus static prose on the log bridge and config.
func observabilityDoc() string {
	var b strings.Builder
	b.WriteString("<!-- autogenerated using internal/docgen -->\n")
	b.WriteString("# che observability\n\n")
	b.WriteString("che emits OTLP telemetry (metrics + mirrored logs) to a local collector, wired in `internal/telemetry`. Disabled by default; a nil provider is a no-op.\n\n")

	b.WriteString("## Metrics\n\n")
	b.WriteString("Every metric is an Int64 monotonic counter on meter `che`.\n\n")
	b.WriteString("| Metric | Type | Labels | Description |\n| --- | --- | --- | --- |\n")
	for _, m := range telemetry.Metrics {
		var labels []string
		for _, l := range m.Labels {
			labels = append(labels, tick(l))
		}
		fmt.Fprintf(&b, "| `%s` | counter | %s | %s |\n", m.Name, strings.Join(labels, ", "), m.Help)
	}

	b.WriteString("\n## Label values\n\n")
	b.WriteString("Observed values per label, curated from the emission sites in `internal/che` (not an enforced enum).\n")
	for _, lv := range labelValues {
		fmt.Fprintf(&b, "\n### `%s`\n\n", lv.Label)
		b.WriteString("| Value | Meaning |\n| --- | --- |\n")
		for _, v := range lv.Values {
			fmt.Fprintf(&b, "| `%s` | %s |\n", v.Value, v.Meaning)
		}
	}

	b.WriteString("\n## Traces\n\n")
	b.WriteString("When `otel.traces` is on, che emits spans on tracer `che`. The tree nests `che run` > `prepare-specs` / `<command>` > `profile` > `<operation>` > external-call spans (`fetch-remote`, `run-script`). Counters record under the active span ctx, so metric exemplars link back to the trace.\n\n")
	b.WriteString("| Span | Attributes | Description |\n| --- | --- | --- |\n")
	for _, s := range telemetry.Spans {
		var attrs []string
		for _, a := range s.Attrs {
			attrs = append(attrs, tick(a))
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", s.Name, strings.Join(attrs, ", "), s.Help)
	}

	b.WriteString("\n## Logs\n\n")
	b.WriteString("When `otel.logs` is on, each che log line is mirrored as an OTLP log record via the log bridge (`Telemetry.LogRecord`): the log title becomes the record event name, the message becomes the body, and the level maps to severity (`debug` -> Debug, everything else -> Info).\n")

	b.WriteString("\n## Config\n\n")
	b.WriteString("The `telemetry.Config` knobs, driven by the `otel:` spec block and `CHE_OTEL_*` env (env wins). See the `otel` group in [che.yml schema](../assets/data/che.schema.json).\n\n")
	b.WriteString("| Knob | Env | Default | Description |\n| --- | --- | --- | --- |\n")
	b.WriteString("| `enabled` | `CHE_OTEL_ENABLED` | `false` | emit OTLP telemetry to the collector |\n")
	b.WriteString("| `endpoint` | `CHE_OTEL_ENDPOINT` | `localhost:4317` (grpc) / `localhost:4318` (http) | OTLP collector endpoint (host:port) |\n")
	b.WriteString("| `protocol` | `CHE_OTEL_PROTOCOL` | `grpc` | OTLP transport: `grpc` \\| `http` |\n")
	b.WriteString("| `metrics` | `CHE_OTEL_METRICS` | `true` | export the metrics above |\n")
	b.WriteString("| `logs` | `CHE_OTEL_LOGS` | `true` | export che log lines as OTLP logs |\n")
	b.WriteString("| `traces` | `CHE_OTEL_TRACES` | `true` | export the spans above |\n")
	return b.String()
}

// [<] 🤖🤖
