package main

// [>] 🤖🤖

import (
	"cmp"
	"encoding/json"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/invopop/jsonschema"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"gitlab.com/konradodwrot/go-modules/che/internal/cli"
	"gitlab.com/konradodwrot/go-modules/che/internal/packages"
	"gitlab.com/konradodwrot/go-modules/che/internal/spec"
)

const (
	schemaPath          = "assets/data/che.schema.json"
	packagesSchemaPath  = "assets/data/packages.schema.json"
	variablesSchemaPath = "assets/data/variables.schema.json"
	cliDocPath          = "docs/cli.md"
	cliUsagePath        = "assets/data/cli-usage.md"
)

func main() {
	must(os.MkdirAll("docs", 0o755))
	root := cli.New().Root()
	root.InitDefaultCompletionCmd()
	must(os.WriteFile(schemaPath, schemaJSON(spec.Schema()), 0o644))
	must(os.WriteFile(packagesSchemaPath, schemaJSON(packages.Schema()), 0o644))
	must(os.WriteFile(variablesSchemaPath, schemaJSON(spec.VariablesFileSchema()), 0o644))
	must(os.WriteFile(cliDocPath, []byte(cliDoc(root)), 0o644))
	must(os.WriteFile(cliUsagePath, []byte(cliUsage(root)), 0o644))
	for _, p := range []string{schemaPath, packagesSchemaPath, variablesSchemaPath, cliDocPath, cliUsagePath} {
		fmt.Println("wrote", p)
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

func schemaJSON(s *jsonschema.Schema) []byte {
	b, err := json.MarshalIndent(s, "", "  ")
	must(err)
	return append(b, '\n')
}

func cutSeg(desc, sep string) (rest, val string) {
	rest, val, _ = strings.Cut(desc, sep)
	return rest, val
}

func tick(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func renderOptionsTable(fs *pflag.FlagSet) string {
	var b strings.Builder
	b.WriteString("| Option | Env | Values | Default | Description |\n| --- | --- | --- | --- | --- |\n")
	fs.VisitAll(func(f *pflag.Flag) {
		desc, env := cutSeg(f.Usage, "; env: ")
		desc, def := cutSeg(desc, "; default: ")
		desc, values := cutSeg(desc, "; values: ")
		env = tick(env)
		values = tick(strings.ReplaceAll(values, " | ", "` \\| `"))
		if values == "" {
			values = "`" + f.Value.Type() + "`"
		}
		def = tick(cmp.Or(def, f.DefValue))
		opt := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			opt = "`-" + f.Shorthand + "`, " + opt
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", opt, env, values, def, desc)
	})
	return b.String()
}

func cliDoc(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- autogenerated using internal/docgen -->\n")
	b.WriteString("# che CLI\n\n")
	b.WriteString(root.Long)
	b.WriteString("\n\n")
	b.WriteString("## Global options\n\n")
	b.WriteString(renderOptionsTable(root.PersistentFlags()))
	b.WriteString("\n## Commands\n")
	walkCommands(root, &b)
	return b.String()
}

func cliUsage(root *cobra.Command) string {
	var rows [][2]string
	var collect func(cmd *cobra.Command, indent string)
	collect = func(cmd *cobra.Command, indent string) {
		for _, sub := range sortedSubs(cmd) {
			rows = append(rows, [2]string{indent + sub.Name(), sub.Short})
			collect(sub, indent+"  ")
		}
	}
	collect(root, "  ")
	width := 0
	for _, r := range rows {
		width = max(width, len(r[0]))
	}
	var b strings.Builder
	b.WriteString("che [command]\n\nAvailable Commands:\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "%-*s  %s\n", width, r[0], r[1])
	}
	b.WriteString("\nFlags:\n")
	b.WriteString(root.PersistentFlags().FlagUsages())
	return b.String()
}

func sortedSubs(cmd *cobra.Command) []*cobra.Command {
	subs := slices.Clone(cmd.Commands())
	subs = slices.DeleteFunc(subs, func(c *cobra.Command) bool { return !c.IsAvailableCommand() })
	slices.SortFunc(subs, func(a, b *cobra.Command) int { return strings.Compare(a.Name(), b.Name()) })
	return subs
}

func walkCommands(cmd *cobra.Command, b *strings.Builder) {
	for _, sub := range sortedSubs(cmd) {
		fmt.Fprintf(b, "\n### `$ %s`\n\n%s.\n", sub.CommandPath(), strings.TrimSuffix(sub.Short, "."))
		if sub.Long != "" {
			fmt.Fprintf(b, "\n%s\n", sub.Long)
		}
		if use := strings.TrimSuffix(sub.UseLine(), " [flags]"); use != sub.CommandPath() {
			fmt.Fprintf(b, "\nUsage: `%s`\n", sub.UseLine())
		}
		if sub.NonInheritedFlags().HasAvailableFlags() {
			fmt.Fprintf(b, "\n%s", renderOptionsTable(sub.NonInheritedFlags()))
		}
		walkCommands(sub, b)
	}
}

// [<] 🤖🤖
