package main

// [>] 🤖🤖

import (
	"encoding/json"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"gitlab.com/konradodwrot/go-modules/che/internal/cli"
	"gitlab.com/konradodwrot/go-modules/che/internal/spec"
)

// docgen renders che's reference docs from the Go source: the che.yml JSON
// Schema (assets/data/che.schema.json) and the CLI reference (docs/cli.md).
// Run from the repo root: `go run ./internal/docgen`.

const (
	schemaPath   = "assets/data/che.schema.json"
	cliDocPath   = "docs/cli.md"
	cliUsagePath = "assets/data/cli-usage.md"
)

func main() {
	must(os.MkdirAll("docs", 0o755))
	root := cli.New().Root()
	must(os.WriteFile(schemaPath, schemaJSON(), 0o644))
	must(os.WriteFile(cliDocPath, []byte(cliDoc(root)), 0o644))
	must(os.WriteFile(cliUsagePath, []byte(cliUsage(root)), 0o644))
	for _, p := range []string{schemaPath, cliDocPath, cliUsagePath} {
		fmt.Println("wrote", p)
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

// schemaJSON marshals spec.Schema() deterministically (properties in struct
// field order, $defs sorted, indented, trailing newline).
func schemaJSON() []byte {
	b, err := json.MarshalIndent(spec.Schema(), "", "  ")
	must(err)
	return append(b, '\n')
}

// optionsTable renders a FlagSet as an Option|Env|Values|Description table.
// Each flag's usage string may carry "; values: <...>" and "; env: <...>"
// segments feeding those columns (values default: the flag's value type;
// flag wins over env).
func optionsTable(fs *pflag.FlagSet) string {
	var b strings.Builder
	b.WriteString("| Option | Env | Values | Description |\n| --- | --- | --- | --- |\n")
	fs.VisitAll(func(f *pflag.Flag) {
		desc, env, values := f.Usage, "", ""
		if i := strings.Index(desc, "; env: "); i >= 0 {
			env = "`" + desc[i+len("; env: "):] + "`"
			desc = desc[:i]
		}
		if i := strings.Index(desc, "; values: "); i >= 0 {
			values = "`" + strings.ReplaceAll(desc[i+len("; values: "):], " | ", "` \\| `") + "`"
			desc = desc[:i]
		}
		if values == "" {
			values = "`" + f.Value.Type() + "`"
		}
		opt := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			opt = "`-" + f.Shorthand + "`, " + opt
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", opt, env, values, desc)
	})
	return b.String()
}

// cliDoc renders the CLI reference: root Long + the global options table,
// then every subcommand (depth-first, name-sorted) with its own table.
func cliDoc(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- autogenerated using internal/docgen -->\n")
	b.WriteString("# che CLI\n\n")
	b.WriteString(root.Long)
	b.WriteString("\n\n")
	b.WriteString("## Global options\n\n")
	b.WriteString(optionsTable(root.PersistentFlags()))
	b.WriteString("\n## Commands\n")
	walkCommands(root, &b)
	return b.String()
}

// cliUsage renders the README usage listing: every command (subcommands
// indented) with its Short, then the global flags. Included by the README
// template via renderMarkdown.
func cliUsage(root *cobra.Command) string {
	var rows [][2]string
	var collect func(cmd *cobra.Command, indent string)
	collect = func(cmd *cobra.Command, indent string) {
		for _, sub := range sortedSubs(cmd) {
			rows = append(rows, [2]string{indent + sub.Name(), sub.Short})
			collect(sub, indent+"  ")
		}
	}
	collect(root, "  ")
	width := 0
	for _, r := range rows {
		width = max(width, len(r[0]))
	}
	var b strings.Builder
	b.WriteString("che [command]\n\nAvailable Commands:\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "%-*s  %s\n", width, r[0], r[1])
	}
	b.WriteString("\nFlags:\n")
	b.WriteString(root.PersistentFlags().FlagUsages())
	return b.String()
}

// sortedSubs lists cmd's available subcommands, name-sorted.
func sortedSubs(cmd *cobra.Command) []*cobra.Command {
	subs := slices.Clone(cmd.Commands())
	subs = slices.DeleteFunc(subs, func(c *cobra.Command) bool { return !c.IsAvailableCommand() })
	slices.SortFunc(subs, func(a, b *cobra.Command) int { return strings.Compare(a.Name(), b.Name()) })
	return subs
}

func walkCommands(cmd *cobra.Command, b *strings.Builder) {
	for _, sub := range sortedSubs(cmd) {
		fmt.Fprintf(b, "\n### `$ %s`\n\n%s.\n", sub.CommandPath(), strings.TrimSuffix(sub.Short, "."))
		if sub.Long != "" {
			fmt.Fprintf(b, "\n%s\n", sub.Long)
		}
		if use := strings.TrimSuffix(sub.UseLine(), " [flags]"); use != sub.CommandPath() {
			fmt.Fprintf(b, "\nUsage: `%s`\n", sub.UseLine())
		}
		if sub.NonInheritedFlags().HasAvailableFlags() {
			fmt.Fprintf(b, "\n%s", optionsTable(sub.NonInheritedFlags()))
		}
		walkCommands(sub, b)
	}
}

// [<] 🤖🤖
