package host

// [>] 🤖🤖

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/konradodwrot/go-modules/che/internal/config"
	"gitlab.com/konradodwrot/go-modules/che/internal/spec"
	"gitlab.com/konradodwrot/go-modules/che/internal/testutil"
	"gitlab.com/konradodwrot/go-modules/che/render/render"
)

func readDest(t *testing.T, root, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(root, rel))
	require.NoErrorf(t, err, "read %s", rel)
	return string(b)
}

// TestRenderRepoReplace: relative dest -> repo file, default writeType
// (overwrite) writes Header + rendered body.
func TestRenderRepoReplace(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"templates/x.ontoRepo.tpl": "hello {{ \"world\" }}\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{Rel: "templates/x.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "out.md"}}}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	assert.Equal(t, "<!-- autogenerated using templates/x.ontoRepo.tpl -->\nhello world\n", readDest(t, root, "out.md"))
}

// TestRenderRepoMergeUpsert: existing wins, defaults fill, sorted, no header.
func TestRenderRepoMergeUpsert(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"templates/env.ontoRepo.tpl": "B=default\nA=default\n",
		".env":                       "B=kept\nC=extra\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{
		Rel:   "templates/env.ontoRepo.tpl",
		Dests: []spec.DestSpec{{Path: ".env", Options: render.Options{WriteType: "mergeUpsert"}}},
	}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	want := "A=default\nB=kept\nC=extra\n"
	assert.Equal(t, want, readDest(t, root, ".env"))
	// stable: re-run yields the same content
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	assert.Equal(t, want, readDest(t, root, ".env"), "merge-upsert must be stable")
}

// TestRenderHostMergeUpsert: an absolute (host) dest also reads Existing, so
// mergeUpsert works on host files.
func TestRenderHostMergeUpsert(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"root/HOME/env.ontoHost.tpl": "B=default\nA=default\n",
	})
	home := filepath.Join(root, "home")
	testutil.WriteFile(t, filepath.Join(home, ".env"), "B=kept\nC=extra\n")
	h := New(root, home, "cli/macos", config.Config{})
	item := spec.FileItem{
		Rel:   "root/HOME/env.ontoHost.tpl",
		Dests: []spec.DestSpec{{Path: "~/.env", Options: render.Options{WriteType: "mergeUpsert"}}},
	}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	assert.Equal(t, "A=default\nB=kept\nC=extra\n", readDest(t, home, ".env"))
}

// TestRenderDerivedDest: a glob-form item (no dest) renders raw (no Compose
// header) to the derived host path, template ext stripped.
func TestRenderDerivedDest(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"root/HOME/.config/zsh/t.ontoHost.tpl": "hello {{ \"world\" }}\n",
	})
	home := filepath.Join(root, "home")
	require.NoError(t, os.MkdirAll(filepath.Join(home, ".config/zsh"), 0o755))
	h := New(root, home, "cli/macos", config.Config{})
	item := spec.FileItem{Rel: "root/HOME/.config/zsh/t.ontoHost.tpl"}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	assert.Equal(t, "hello world\n", readDest(t, home, ".config/zsh/t"), "raw body without header")
}

// TestRenderRepoMultiDestAtInclude: one dest inlines @-includes, the other keeps them.
func TestRenderRepoMultiDestAtInclude(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"templates/agents.ontoRepo.tpl": "@inc.md\n",
		"inc.md":                        "INLINED\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{
		Rel: "templates/agents.ontoRepo.tpl",
		Dests: []spec.DestSpec{
			{Path: "CLAUDE.md"},
			{Path: "AGENTS.md", Options: render.Options{RenderReferencedFiles: true}},
		},
	}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	assert.Contains(t, readDest(t, root, "CLAUDE.md"), "@inc.md", "CLAUDE.md must keep the @-include")
	agents := readDest(t, root, "AGENTS.md")
	assert.Contains(t, agents, "INLINED")
	assert.NotContains(t, agents, "@inc.md", "AGENTS.md must inline the @-include")
}

// TestRenderContinuesOnError: a failing template logs render(fail), the next
// item still renders, and the op returns the failure.
func TestRenderContinuesOnError(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"templates/ok.ontoRepo.tpl": "fine\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	items := []spec.FileItem{
		{Rel: "templates/missing.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "bad.md"}}},
		{Rel: "templates/ok.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "ok.md"}}},
	}
	out, err := testutil.CaptureStdout(t, func() error { return h.RenderTemplates(items, false) })
	require.Error(t, err, "RenderTemplates must return the collected failure")
	testutil.WantLines(t, out,
		"render(fail): templates/missing.ontoRepo.tpl: ",
		"render(create): "+filepath.Join(root, "ok.md"))
	assert.Contains(t, readDest(t, root, "ok.md"), "fine", "second template must render after the first failed")
	_, serr := os.Stat(filepath.Join(root, "bad.md"))
	assert.True(t, os.IsNotExist(serr), "failed template must not produce bad.md")
}

// TestRenderSkipSecrets: op:// source skipped when skipSecrets is set.
func TestRenderSkipSecrets(t *testing.T) {
	root := testutil.Tree(t, map[string]string{
		"templates/s.ontoRepo.tpl": "TOKEN={{ op \"op://x/y/z\" }}\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{Rel: "templates/s.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "out"}}}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, true))
	_, err := os.Stat(filepath.Join(root, "out"))
	assert.True(t, os.IsNotExist(err), "secret-ref dest must be skipped")
}

// TestRenderRemoteSourceWithCtx: @-prefixed remote source fetched through the
// RemoteFetcher, ctx as root context, skipAutoGeneratedHeader -> no header.
func TestRenderRemoteSourceWithCtx(t *testing.T) {
	root := testutil.Tree(t, nil)
	h := New(root, "/home/x", "cli/macos", config.Config{}).WithFetcher(testutil.RemoteMockFetcher{
		"gitlab.com/acme/tools//snippets/agent.md": "name: RO-{{ .repo }}\n",
	})
	item := spec.FileItem{
		Rel:   "@gitlab.com/acme/tools//snippets/agent.md",
		Ctx:   map[string]string{"repo": "Notes"},
		Dests: []spec.DestSpec{{Path: ".claude/agents/ro.md", Options: render.Options{SkipAutoGeneratedHeader: true}}},
	}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, false))
	assert.Equal(t, "name: RO-Notes\n", readDest(t, root, ".claude/agents/ro.md"))
}

// TestRenderRemoteSkipSecrets: remote source carrying an op:// ref skipped
// when skipSecrets is set.
func TestRenderRemoteSkipSecrets(t *testing.T) {
	root := testutil.Tree(t, nil)
	h := New(root, "/home/x", "cli/macos", config.Config{}).WithFetcher(testutil.RemoteMockFetcher{
		"gitlab.com/acme/tools//snippets/s.md": "TOKEN={{ op \"op://x/y/z\" }}\n",
	})
	item := spec.FileItem{
		Rel:   "@gitlab.com/acme/tools//snippets/s.md",
		Dests: []spec.DestSpec{{Path: "out"}},
	}
	require.NoError(t, h.RenderTemplates([]spec.FileItem{item}, true))
	_, err := os.Stat(filepath.Join(root, "out"))
	assert.True(t, os.IsNotExist(err), "remote secret-ref dest must be skipped")
}

// TestRenderRemoteFetchError: a failing fetch surfaces as a render failure,
// dest untouched.
func TestRenderRemoteFetchError(t *testing.T) {
	root := testutil.Tree(t, nil)
	h := New(root, "/home/x", "cli/macos", config.Config{}).WithFetcher(testutil.RemoteMockFetcher{})
	item := spec.FileItem{
		Rel:   "@gitlab.com/acme/tools//snippets/absent.md",
		Dests: []spec.DestSpec{{Path: "out"}},
	}
	_, err := testutil.CaptureStdout(t, func() error { return h.RenderTemplates([]spec.FileItem{item}, false) })
	require.Error(t, err, "RenderTemplates must return the fetch failure")
	_, serr := os.Stat(filepath.Join(root, "out"))
	assert.True(t, os.IsNotExist(serr), "failed remote fetch must not produce out")
}

// [<] 🤖🤖
