package host

// [>] 🤖🤖

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gitlab.com/konradodwrot/go/che/internal/spec"
	"gitlab.com/konradodwrot/go/render-files/render"
)

// writeRepo writes rel->content under a temp repo root, returns the root.
func writeRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func readDest(t *testing.T, root, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(b)
}

// TestRenderRepoReplace: default writeType (overwrite) writes Header + rendered body.
func TestRenderRepoReplace(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/x.repo.tpl": "hello {{ \"world\" }}\n",
	})
	h := New(root, "/home/x", "cli/macos", DryRunOff)
	item := spec.FileItem{Rel: "templates/x.repo.tpl", Dests: []spec.DestSpec{{Path: "out.md"}}}
	if err := h.RenderRepoTemplates([]spec.FileItem{item}); err != nil {
		t.Fatal(err)
	}
	got := readDest(t, root, "out.md")
	want := "<!-- autogenerated using templates/x.repo.tpl -->\nhello world\n"
	if got != want {
		t.Errorf("replace output = %q, want %q", got, want)
	}
}

// TestRenderRepoMergeUpsert: existing wins, defaults fill, sorted, no header.
func TestRenderRepoMergeUpsert(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/env.repo.tpl": "B=default\nA=default\n",
		".env":                   "B=kept\nC=extra\n",
	})
	h := New(root, "/home/x", "cli/macos", DryRunOff)
	item := spec.FileItem{
		Rel:   "templates/env.repo.tpl",
		Dests: []spec.DestSpec{{Path: ".env", Options: render.Options{WriteType: "mergeUpsert"}}},
	}
	if err := h.RenderRepoTemplates([]spec.FileItem{item}); err != nil {
		t.Fatal(err)
	}
	got := readDest(t, root, ".env")
	want := "A=default\nB=kept\nC=extra\n"
	if got != want {
		t.Errorf("merge-upsert output = %q, want %q", got, want)
	}
	// stable: re-run yields the same content
	if err := h.RenderRepoTemplates([]spec.FileItem{item}); err != nil {
		t.Fatal(err)
	}
	if again := readDest(t, root, ".env"); again != want {
		t.Errorf("merge-upsert not stable: %q", again)
	}
}

// TestRenderRepoMultiDestAtInclude: one dest inlines @-includes, the other keeps them.
func TestRenderRepoMultiDestAtInclude(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/agents.repo.tpl": "@inc.md\n",
		"inc.md":                    "INLINED\n",
	})
	h := New(root, "/home/x", "cli/macos", DryRunOff)
	item := spec.FileItem{
		Rel: "templates/agents.repo.tpl",
		Dests: []spec.DestSpec{
			{Path: "CLAUDE.md"},
			{Path: "AGENTS.md", Options: render.Options{RenderReferencedFiles: true}},
		},
	}
	if err := h.RenderRepoTemplates([]spec.FileItem{item}); err != nil {
		t.Fatal(err)
	}
	claude := readDest(t, root, "CLAUDE.md")
	agents := readDest(t, root, "AGENTS.md")
	if !strings.Contains(claude, "@inc.md") {
		t.Errorf("CLAUDE.md should keep @-include, got %q", claude)
	}
	if !strings.Contains(agents, "INLINED") || strings.Contains(agents, "@inc.md") {
		t.Errorf("AGENTS.md should inline @-include, got %q", agents)
	}
}

// TestRenderRepoDryRunSkipSecrets: op:// source skipped when the env flag is set.
func TestRenderRepoDryRunSkipSecrets(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/s.repo.tpl": "TOKEN={{ op \"op://x/y/z\" }}\n",
	})
	t.Setenv("CHE_DRY_RUN_RENDER_SECRETS", "1")
	h := New(root, "/home/x", "cli/macos", DryRunOff)
	item := spec.FileItem{Rel: "templates/s.repo.tpl", Dests: []spec.DestSpec{{Path: "out"}}}
	if err := h.RenderRepoTemplates([]spec.FileItem{item}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "out")); !os.IsNotExist(err) {
		t.Errorf("secret-ref dest should be skipped, but out exists")
	}
}

// [<] 🤖🤖
