package host

// [>] 🤖🤖

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gitlab.com/konradodwrot/go-modules/che/internal/config"
	"gitlab.com/konradodwrot/go-modules/che/internal/spec"
	"gitlab.com/konradodwrot/go-modules/che/internal/testutil"
	"gitlab.com/konradodwrot/go-modules/che/render/render"
)

// writeRepo writes rel->content under a temp repo root, returns the root.
func writeRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func readDest(t *testing.T, root, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(b)
}

// TestRenderRepoReplace: relative dest -> repo file, default writeType
// (overwrite) writes Header + rendered body.
func TestRenderRepoReplace(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/x.ontoRepo.tpl": "hello {{ \"world\" }}\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{Rel: "templates/x.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "out.md"}}}
	if err := h.RenderTemplates([]spec.FileItem{item}, false); err != nil {
		t.Fatal(err)
	}
	got := readDest(t, root, "out.md")
	want := "<!-- autogenerated using templates/x.ontoRepo.tpl -->\nhello world\n"
	if got != want {
		t.Errorf("replace output = %q, want %q", got, want)
	}
}

// TestRenderRepoMergeUpsert: existing wins, defaults fill, sorted, no header.
func TestRenderRepoMergeUpsert(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/env.ontoRepo.tpl": "B=default\nA=default\n",
		".env":                       "B=kept\nC=extra\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{
		Rel:   "templates/env.ontoRepo.tpl",
		Dests: []spec.DestSpec{{Path: ".env", Options: render.Options{WriteType: "mergeUpsert"}}},
	}
	if err := h.RenderTemplates([]spec.FileItem{item}, false); err != nil {
		t.Fatal(err)
	}
	got := readDest(t, root, ".env")
	want := "A=default\nB=kept\nC=extra\n"
	if got != want {
		t.Errorf("merge-upsert output = %q, want %q", got, want)
	}
	// stable: re-run yields the same content
	if err := h.RenderTemplates([]spec.FileItem{item}, false); err != nil {
		t.Fatal(err)
	}
	if again := readDest(t, root, ".env"); again != want {
		t.Errorf("merge-upsert not stable: %q", again)
	}
}

// TestRenderHostMergeUpsert: an absolute (host) dest also reads Existing, so
// mergeUpsert works on host files.
func TestRenderHostMergeUpsert(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"root/HOME/env.ontoHost.tpl": "B=default\nA=default\n",
	})
	home := filepath.Join(root, "home")
	if err := os.MkdirAll(home, 0o755); err != nil {
		t.Fatal(err)
	}
	dest := filepath.Join(home, ".env")
	if err := os.WriteFile(dest, []byte("B=kept\nC=extra\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	h := New(root, home, "cli/macos", config.Config{})
	item := spec.FileItem{
		Rel:   "root/HOME/env.ontoHost.tpl",
		Dests: []spec.DestSpec{{Path: "~/.env", Options: render.Options{WriteType: "mergeUpsert"}}},
	}
	if err := h.RenderTemplates([]spec.FileItem{item}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	want := "A=default\nB=kept\nC=extra\n"
	if string(got) != want {
		t.Errorf("host merge-upsert output = %q, want %q", got, want)
	}
}

// TestRenderDerivedDest: a glob-form item (no dest) renders raw (no Compose
// header) to the derived host path, template ext stripped.
func TestRenderDerivedDest(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"root/HOME/.config/zsh/t.ontoHost.tpl": "hello {{ \"world\" }}\n",
	})
	home := filepath.Join(root, "home")
	if err := os.MkdirAll(filepath.Join(home, ".config/zsh"), 0o755); err != nil {
		t.Fatal(err)
	}
	h := New(root, home, "cli/macos", config.Config{})
	item := spec.FileItem{Rel: "root/HOME/.config/zsh/t.ontoHost.tpl"}
	if err := h.RenderTemplates([]spec.FileItem{item}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(home, ".config/zsh/t"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "hello world\n" {
		t.Errorf("derived output = %q, want raw body without header", got)
	}
}

// TestRenderRepoMultiDestAtInclude: one dest inlines @-includes, the other keeps them.
func TestRenderRepoMultiDestAtInclude(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/agents.ontoRepo.tpl": "@inc.md\n",
		"inc.md":                        "INLINED\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{
		Rel: "templates/agents.ontoRepo.tpl",
		Dests: []spec.DestSpec{
			{Path: "CLAUDE.md"},
			{Path: "AGENTS.md", Options: render.Options{RenderReferencedFiles: true}},
		},
	}
	if err := h.RenderTemplates([]spec.FileItem{item}, false); err != nil {
		t.Fatal(err)
	}
	claude := readDest(t, root, "CLAUDE.md")
	agents := readDest(t, root, "AGENTS.md")
	if !strings.Contains(claude, "@inc.md") {
		t.Errorf("CLAUDE.md should keep @-include, got %q", claude)
	}
	if !strings.Contains(agents, "INLINED") || strings.Contains(agents, "@inc.md") {
		t.Errorf("AGENTS.md should inline @-include, got %q", agents)
	}
}

// TestRenderContinuesOnError: a failing template logs render(fail), the next
// item still renders, and the op returns the failure.
func TestRenderContinuesOnError(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/ok.ontoRepo.tpl": "fine\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	items := []spec.FileItem{
		{Rel: "templates/missing.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "bad.md"}}},
		{Rel: "templates/ok.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "ok.md"}}},
	}
	out, err := testutil.CaptureStdout(t, func() error { return h.RenderTemplates(items, false) })
	if err == nil {
		t.Fatal("RenderTemplates must return the collected failure")
	}
	testutil.WantLines(t, out,
		"render(fail): templates/missing.ontoRepo.tpl: ",
		"render(create): "+filepath.Join(root, "ok.md"))
	if got := readDest(t, root, "ok.md"); !strings.Contains(got, "fine") {
		t.Errorf("second template not rendered after first failed: %q", got)
	}
	if _, serr := os.Stat(filepath.Join(root, "bad.md")); !os.IsNotExist(serr) {
		t.Error("failed template unexpectedly produced bad.md")
	}
}

// TestRenderSkipSecrets: op:// source skipped when skipSecrets is set.
func TestRenderSkipSecrets(t *testing.T) {
	root := writeRepo(t, map[string]string{
		"templates/s.ontoRepo.tpl": "TOKEN={{ op \"op://x/y/z\" }}\n",
	})
	h := New(root, "/home/x", "cli/macos", config.Config{})
	item := spec.FileItem{Rel: "templates/s.ontoRepo.tpl", Dests: []spec.DestSpec{{Path: "out"}}}
	if err := h.RenderTemplates([]spec.FileItem{item}, true); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "out")); !os.IsNotExist(err) {
		t.Errorf("secret-ref dest should be skipped, but out exists")
	}
}

// [<] 🤖🤖
