// Package spec parses, schema-validates, and resolves che.yml: profile recipes, include/exclude sets, spec and profile sources.
package spec

// [>] 🤖🤖

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"gitlab.com/konradodwrot/go-modules/che/render/render"
)

const (
	TmplExt = ".tpl"
	CpExt   = ".ontoHost.cp"
	// DefaultWorkingDir is the load-ops source tree when options.workingDirectory
	// is unset: the checkout itself.
	DefaultWorkingDir = "."
)

// tmplExts are the accepted template suffixes, longest first (informational
// only: the dest path decides host vs repo).
var tmplExts = []string{".ontoHost.tpl", ".ontoRepo.tpl", ".tpl"}

// IsTmplSrc reports whether rel is a template source (any accepted suffix).
func IsTmplSrc(rel string) bool { return strings.HasSuffix(rel, TmplExt) }

// RemoteSrcPrefix marks a renderTemplates source as remote:
// @<repo>//<path>[?ref=<ref>], fetched at render time.
const RemoteSrcPrefix = "@"

// IsRemoteSrc reports whether source is a remote template source.
func IsRemoteSrc(source string) bool { return strings.HasPrefix(source, RemoteSrcPrefix) }

// RemoteSrcRef strips the remote marker, yielding the fetchable ref.
func RemoteSrcRef(source string) string { return strings.TrimPrefix(source, RemoteSrcPrefix) }

// TrimTmplExt strips the template suffix (longest first), yielding the derived dest.
func TrimTmplExt(rel string) string {
	for _, ext := range tmplExts {
		if trimmed, ok := strings.CutSuffix(rel, ext); ok {
			return trimmed
		}
	}
	return rel
}

func (l *linkEntry) UnmarshalYAML(value *yaml.Node) error {
	type alias linkEntry
	return decodeScalarOr(value, &l.glob, (*alias)(l))
}

// decodeScalarOr implements the scalar-or-object union form shared by every
// spec entry type: a scalar node's value lands in scalar, anything else
// decodes into obj (an alias type, sidestepping UnmarshalYAML recursion).
func decodeScalarOr[T any](value *yaml.Node, scalar *string, obj *T) error {
	if value.Kind == yaml.ScalarNode {
		*scalar = value.Value
		return nil
	}
	return value.Decode(obj)
}

func (d *DestSpec) UnmarshalYAML(value *yaml.Node) error {
	var raw struct {
		Path    string      `yaml:"path"`
		Options optionsSpec `yaml:"options"`
	}
	if err := decodeScalarOr(value, &d.Path, &raw); err != nil {
		return err
	}
	if raw.Path != "" {
		d.Path = raw.Path
	}
	d.opts = raw.Options
	d.Options = raw.Options.over(render.Options{})
	return nil
}

func (o optionsSpec) over(base render.Options) render.Options {
	if o.WriteType != nil {
		base.WriteType = *o.WriteType
	}
	if o.SkipAutoGeneratedHeader != nil {
		base.SkipAutoGeneratedHeader = *o.SkipAutoGeneratedHeader
	}
	if o.RenderReferencedFiles != nil {
		base.RenderReferencedFiles = *o.RenderReferencedFiles
	}
	return base
}

func (d *dirSpec) UnmarshalYAML(value *yaml.Node) error {
	type alias dirSpec
	return decodeScalarOr(value, &d.glob, (*alias)(d))
}

func (f *fileSpec) UnmarshalYAML(value *yaml.Node) error {
	type alias fileSpec
	return decodeScalarOr(value, &f.glob, (*alias)(f))
}

// LinkDestRel is a link item's repo-relative dest path: the rewritten
// Dests[0] when a dest rule applied, else the source Rel (1:1).
func LinkDestRel(it FileItem) string {
	if len(it.Dests) > 0 {
		return it.Dests[0].Path
	}
	return it.Rel
}

// Load parses che.yml: reserved top-level keys options/env/include, every
// other key one ProfileRecipe (stamped with its name).
func Load(path string) (*Doc, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("spec not found: %s", path)
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	d := &Doc{}
	if len(doc.Content) == 0 {
		return d, nil
	}
	m := doc.Content[0]
	for i := 0; i+1 < len(m.Content); i += 2 {
		key, node := m.Content[i].Value, m.Content[i+1]
		if err := d.decodeKey(key, node); err != nil {
			return nil, err
		}
	}
	return d, nil
}

// decodeKey decodes one top-level entry: a reserved key or a profile block.
func (d *Doc) decodeKey(key string, node *yaml.Node) error {
	switch key {
	case "options":
		return node.Decode(&d.Options)
	case "env":
		return node.Decode(&d.Env)
	case "include":
		var inc struct {
			Sources []string `yaml:"sources"`
		}
		if err := node.Decode(&inc); err != nil {
			return fmt.Errorf("parse include: %w", err)
		}
		for _, s := range inc.Sources {
			d.Include = append(d.Include, SpecSourceRecipe{SourceRecipe{URI: s}})
		}
		return nil
	default:
		var ps ProfileRecipe
		if err := node.Decode(&ps); err != nil {
			return fmt.Errorf("parse profile %q: %w", key, err)
		}
		ps.Source.ProfileName = key
		d.ProfileRecipes = append(d.ProfileRecipes, ps)
		return nil
	}
}

// [<] 🤖🤖
