package spec

// [>] 🤖🤖

import (
	"embed"
	"maps"
	"path/filepath"
	"slices"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/konradodwrot/go-modules/che/internal/testutil"
	"gitlab.com/konradodwrot/go-modules/lib/testyml"
)

//go:embed all:testdata
var td embed.FS

type permWant struct {
	Owner      string `yaml:"owner"`
	OwnerGroup string `yaml:"ownerGroup"`
	Chmod      string `yaml:"chmod"`
}

type optWant struct {
	WriteType               string `yaml:"writeType"`
	SkipAutoGeneratedHeader bool   `yaml:"skipAutoGeneratedHeader"`
	RenderReferencedFiles   bool   `yaml:"renderReferencedFiles"`
}

type refWant struct {
	Source  string            `yaml:"source"`
	Profile string            `yaml:"profile"`
	Env     map[string]string `yaml:"env"`
}

// wantSet is make_profile's domain projection set, carried inside
// expected/notExpected/contains (the canonical schema's one exception).
type wantSet struct {
	testyml.Expected[struct{}] `yaml:",inline"`

	Links         []string                     `yaml:"links"`
	Copies        []string                     `yaml:"copies"`
	Templates     []string                     `yaml:"templates"`
	Dirs          []string                     `yaml:"dirs"`
	ExtraDirs     []string                     `yaml:"extraDirs"`
	Scripts       []string                     `yaml:"scripts"`
	Services      []string                     `yaml:"services"`
	Perms         map[string]permWant          `yaml:"perms"`
	Dests         map[string][]string          `yaml:"dests"`
	Ctx           map[string]map[string]string `yaml:"ctx"`
	TemplateDests [][]string                   `yaml:"templateDests"`
	TemplateOpts  [][]optWant                  `yaml:"templateOpts"`
	Refs          []refWant                    `yaml:"refs"`
}

// makeProfileCase is make_profile's spec case: the canonical shape plus contains.
type makeProfileCase struct {
	Name        string          `yaml:"name"`
	Context     testyml.Context `yaml:"context"`
	Input       testyml.Input   `yaml:"input"`
	Expected    *wantSet        `yaml:"expected"`
	NotExpected *wantSet        `yaml:"notExpected"`
	Contains    *wantSet        `yaml:"contains"`
}

func rels(items []FileItem) []string {
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = it.Rel
	}
	return out
}

func destPaths(item FileItem) []string {
	out := make([]string, len(item.Dests))
	for i, d := range item.Dests {
		out[i] = d.Path
	}
	return out
}

// extraDirs picks the mkdirs entries out of the merged MkDirs list (the
// ancestor items carry no Dests).
func extraDirs(ops OperationRecipes) []FileItem {
	var out []FileItem
	for _, it := range ops.MkDirs.Dirs {
		if len(it.Dests) > 0 {
			out = append(out, it)
		}
	}
	return out
}

func extraDirPaths(ops OperationRecipes) []string {
	items := extraDirs(ops)
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = it.Dests[0].Path
	}
	return out
}

func findItem(ops OperationRecipes, key string) *FileItem {
	for _, items := range [][]FileItem{ops.Link.Links, ops.Copy.Copies, ops.RenderTemplates.Templates} {
		if i := slices.IndexFunc(items, func(it FileItem) bool { return it.Rel == key }); i >= 0 {
			return &items[i]
		}
	}
	extras := extraDirs(ops)
	if i := slices.IndexFunc(extras, func(it FileItem) bool { return it.Dests[0].Path == key }); i >= 0 {
		return &extras[i]
	}
	return nil
}

func projections(ops OperationRecipes) map[string][]string {
	return map[string][]string{
		"links":     rels(ops.Link.Links),
		"copies":    rels(ops.Copy.Copies),
		"templates": rels(ops.RenderTemplates.Templates),
		"dirs":      ops.PruneLinks.Dirs,
		"extraDirs": extraDirPaths(ops),
		"scripts":   ops.RunScripts.Scripts,
		"services":  ops.Services.Services,
	}
}

func (w wantSet) lists() map[string][]string {
	return map[string][]string{
		"links":     w.Links,
		"copies":    w.Copies,
		"templates": w.Templates,
		"dirs":      w.Dirs,
		"extraDirs": w.ExtraDirs,
		"scripts":   w.Scripts,
		"services":  w.Services,
	}
}

func assertWant(t *testing.T, ops OperationRecipes, refs []ProfileSourceRecipe, w wantSet) {
	t.Helper()
	got := projections(ops)
	for key, want := range w.lists() {
		if want != nil {
			assert.Equal(t, want, got[key], key)
		}
	}
	for key, p := range w.Perms {
		item := findItem(ops, key)
		if !assert.NotNil(t, item, "perms: %q not resolved", key) {
			continue
		}
		if (p.Owner != "" && item.Owner != p.Owner) ||
			(p.OwnerGroup != "" && item.OwnerGroup != p.OwnerGroup) ||
			(p.Chmod != "" && item.Chmod != p.Chmod) {
			t.Errorf("perms[%q] = %+v, want %+v", key, item.Perms, p)
		}
	}
	for key, want := range w.Dests {
		item := findItem(ops, key)
		if !assert.NotNil(t, item, "dests: %q not resolved", key) {
			continue
		}
		got := destPaths(*item)
		if len(want) == 0 {
			assert.Empty(t, got, "dests[%q]", key)
			continue
		}
		assert.Equal(t, want, got, "dests[%q]", key)
	}
	for key, want := range w.Ctx {
		item := findItem(ops, key)
		if !assert.NotNil(t, item, "ctx: %q not resolved", key) {
			continue
		}
		assert.True(t, maps.Equal(item.Ctx, want), "ctx[%q] = %v, want %v", key, item.Ctx, want)
	}
	tmpls := ops.RenderTemplates.Templates
	for i, want := range w.TemplateDests {
		if !assert.Less(t, i, len(tmpls), "templateDests[%d]: only %d templates resolved", i, len(tmpls)) {
			continue
		}
		assert.Equal(t, want, destPaths(tmpls[i]), "templateDests[%d]", i)
	}
	for i, opts := range w.TemplateOpts {
		if !assert.Less(t, i, len(tmpls), "templateOpts[%d]: only %d templates resolved", i, len(tmpls)) {
			continue
		}
		dests := tmpls[i].Dests
		if !assert.Len(t, dests, len(opts), "templateOpts[%d]", i) {
			continue
		}
		for j, o := range opts {
			got := optWant{
				WriteType:               dests[j].Options.WriteType,
				SkipAutoGeneratedHeader: dests[j].Options.SkipAutoGeneratedHeader,
				RenderReferencedFiles:   dests[j].Options.RenderReferencedFiles,
			}
			assert.Equal(t, o, got, "templateOpts[%d][%d]", i, j)
		}
	}
	if w.Refs != nil {
		require.Len(t, refs, len(w.Refs))
		for i, p := range w.Refs {
			got := refs[i]
			if got.URI != p.Source || got.ProfileName != p.Profile || !maps.Equal(got.Env, p.Env) {
				t.Errorf("refs[%d] = %+v, want %+v", i, got, p)
			}
		}
	}
}

func assertMembership(t *testing.T, ops OperationRecipes, w *wantSet, present bool) {
	t.Helper()
	if w == nil {
		return
	}
	got := projections(ops)
	for key, entries := range w.lists() {
		for _, e := range entries {
			assert.Equal(t, present, slices.Contains(got[key], e), "%s: %q (%v)", key, e, got[key])
		}
	}
}

// loadAndMake loads dir's che.yml, anchors every recipe at dir, and resolves
// the named profile.
func loadAndMake(dir, profile string) (OperationRecipes, []ProfileSourceRecipe, error) {
	d, err := Load(filepath.Join(dir, "che.yml"))
	if err != nil {
		return OperationRecipes{}, nil, err
	}
	for i := range d.ProfileRecipes {
		d.ProfileRecipes[i].Source.DirectoryPath = dir
	}
	rec, err := FindRecipe(d.ProfileRecipes, profile)
	if err != nil {
		return OperationRecipes{}, nil, err
	}
	return rec.MakeProfile(d.ProfileRecipes)
}

func TestMakeProfile(t *testing.T) {
	testyml.Run(t, td, "testdata/spec/funcs/make_profile.test.spec.yml", func(t *testing.T, c makeProfileCase) {
		dir := t.TempDir()
		testyml.CopyDir(t, td, c.Context.Pwd, dir)
		if name := c.Input.Args.String(t, 0); name != "" {
			testutil.WriteTree(t, dir, map[string]string{"che.yml": testutil.Spec(t, name)})
		}
		testutil.GitRepo(t, dir)
		ops, refs, err := loadAndMake(dir, c.Input.Args.String(t, 1))
		if c.Expected != nil && c.Expected.Check(t, err) {
			return
		}
		require.NoError(t, err)
		if c.Expected != nil {
			assertWant(t, ops, refs, *c.Expected)
		}
		assertMembership(t, ops, c.Contains, true)
		assertMembership(t, ops, c.NotExpected, false)
	})
}

func TestEligibleRecipes(t *testing.T) {
	testyml.Eq(t, td, "testdata/spec/funcs/eligible_recipes.test.spec.yml", func(t *testing.T, c testyml.Case[[]string]) ([]string, error) {
		a := c.Input.Args
		dir := testutil.Tree(t, map[string]string{"che.yml": testutil.Spec(t, a.String(t, 0))})
		d, err := Load(filepath.Join(dir, "che.yml"))
		require.NoError(t, err)
		return EligibleRecipes(d.ProfileRecipes, a.String(t, 3), a.Bool(t, 4), stubEvaluator(a.String(t, 1), a.Bool(t, 2)).EvalExecIf)
	})
}

// [<] 🤖🤖
