package spec

// [>] 🤖🤖

import (
	"fmt"
	"os"
	"slices"
	"strings"
	"sync"

	"gopkg.in/yaml.v3"

	"gitlab.com/konradodwrot/go-modules/che/internal/log"
	"gitlab.com/konradodwrot/go-modules/che/internal/spec/envinterp"
	"gitlab.com/konradodwrot/go-modules/che/render/render"
)

const (
	TemplateExt       = ".tpl"
	CpExt             = ".ontoHost.cp"
	DefaultWorkingDir = "."
)

var templateExts = []string{".ontoHost.tpl", ".ontoRepo.tpl", ".tpl"}

func IsTemplateSrc(rel string) bool { return strings.HasSuffix(rel, TemplateExt) }

const RemoteSrcPrefix = render.GitMarker

func IsRemoteSrc(source string) bool {
	_, ok := render.CutGitMarker(source)
	return ok
}

func (r ProfileRecipe) IncludedProfileRefs() []string {
	var out []string
	for _, ref := range r.Include.Profiles {
		out = append(out, ref.DisplayRef())
	}
	return out
}

func (r ProfileRecipe) SourcedRefs() []ProfileSourceRecipe {
	var out []ProfileSourceRecipe
	for _, ref := range r.Include.Profiles {
		if ref.URI != "" {
			out = append(out, ref)
		}
	}
	return out
}

// ProfilePathSep joins the profile names of a ref's path: a::b names b as included by top-level a.
const ProfilePathSep = "::"

// SplitProfilePath cuts the first profile name off a ref's profile path.
func SplitProfilePath(path string) (head, rest string) {
	head, rest, _ = strings.Cut(path, ProfilePathSep)
	return head, rest
}

func expandProfileRefs(refs []ProfileSourceRecipe) []ProfileSourceRecipe {
	var out []ProfileSourceRecipe
	for _, ref := range refs {
		out = append(out, ref.Expand()...)
	}
	return out
}

func RemoteSrcRef(source string) string {
	rest, _ := render.CutGitMarker(source)
	return rest
}

func TrimTemplateExt(rel string) string {
	for _, ext := range templateExts {
		if trimmed, ok := strings.CutSuffix(rel, ext); ok {
			return trimmed
		}
	}
	return rel
}

func (s *SourceSpec) UnmarshalYAML(value *yaml.Node) error {
	type alias SourceSpec
	if err := decodeScalarOr(value, &s.raw, (*alias)(s)); err != nil {
		return err
	}
	if s.raw == "" && s.URL == "" {
		return fmt.Errorf("source object requires url")
	}
	return nil
}

// String renders the source in the loader's string form: the scalar verbatim, an object as git::<url>[@<ref>][//<filepath>].
func (s SourceSpec) String() string {
	if s.raw != "" || s.URL == "" {
		return s.raw
	}
	out := RemoteSrcPrefix + s.URL
	if s.Ref != "" {
		out += "@" + s.Ref
	}
	if s.FilePath != "" {
		out += "//" + strings.TrimPrefix(s.FilePath, "/")
	}
	return out
}

// [why] every reader of a node's source speaks the string form: an object source decodes once,
// here, into the scalar the rest of the loader already understands
func flattenObjectSource(value *yaml.Node) (*yaml.Node, error) {
	if value.Kind != yaml.MappingNode {
		return value, nil
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		if value.Content[i].Value != "source" || value.Content[i+1].Kind != yaml.MappingNode {
			continue
		}
		var src SourceSpec
		if err := value.Content[i+1].Decode(&src); err != nil {
			return nil, err
		}
		rest := *value
		rest.Content = slices.Clone(value.Content)
		rest.Content[i+1] = &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: src.String()}
		return &rest, nil
	}
	return value, nil
}

func (l *linkEntry) UnmarshalYAML(value *yaml.Node) error {
	node, err := flattenObjectSource(value)
	if err != nil {
		return err
	}
	if rule, rest, ok := takeScalarDest(node); ok {
		l.DestRule = rule
		node = rest
	}
	type alias linkEntry
	return decodeScalarOr(node, &l.glob, (*alias)(l))
}

func decodeScalarOr[T any](value *yaml.Node, scalar *string, obj *T) error {
	if value.Kind == yaml.ScalarNode {
		*scalar = value.Value
		return nil
	}
	return value.Decode(obj)
}

func (d *DestSpec) UnmarshalYAML(value *yaml.Node) error {
	var raw struct {
		Path    string      `yaml:"path"`
		Options optionsSpec `yaml:"options"`
	}
	if err := decodeScalarOr(value, &d.Path, &raw); err != nil {
		return err
	}
	if raw.Path != "" {
		d.Path = raw.Path
	}
	d.opts = raw.Options
	d.Options = raw.Options.over(render.Options{})
	return nil
}

func (o optionsSpec) over(base render.Options) render.Options {
	if o.WriteType != nil {
		base.WriteType = *o.WriteType
	}
	if o.CommentPrefix != nil {
		base.CommentPrefix = *o.CommentPrefix
	}
	if o.SkipAutoGeneratedHeader != nil {
		base.SkipAutoGeneratedHeader = *o.SkipAutoGeneratedHeader
	}
	if o.RenderReferencedFiles != nil {
		base.RenderReferencedFiles = *o.RenderReferencedFiles
	}
	if o.MergeUpdate != nil {
		base.MergeUpdate = *o.MergeUpdate
	}
	return base
}

func (s *Scalar) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("want a scalar, got kind %v", value.Kind)
	}
	*s = Scalar(value.Value)
	return nil
}

func (s *StringOrList) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind == yaml.ScalarNode {
		*s = StringOrList{value.Value}
		return nil
	}
	var list []string
	if err := value.Decode(&list); err != nil {
		return err
	}
	*s = list
	return nil
}

func (d *dirSpec) UnmarshalYAML(value *yaml.Node) error {
	type alias dirSpec
	return decodeScalarOr(value, &d.glob, (*alias)(d))
}

func (c *copyNode) UnmarshalYAML(value *yaml.Node) error {
	type alias copyNode
	return decodeTreeNode(value, &c.glob, &c.DestRule, &c.Dest, (*alias)(c))
}

func (t *templateNode) UnmarshalYAML(value *yaml.Node) error {
	type alias templateNode
	if err := decodeTreeNode(value, &t.glob, &t.DestRule, &t.Dest, (*alias)(t)); err != nil {
		return err
	}
	if legacy := ctxAlias(value, "renderTemplates node"); legacy != nil {
		t.Variables = mergeEnv(legacy, t.Variables)
	}
	return nil
}

func decodeTreeNode[T any](value *yaml.Node, glob, destRule *string, dest *[]DestSpec, obj *T) error {
	node, err := flattenObjectSource(value)
	if err != nil {
		return err
	}
	scalarDest, rest, hasScalarDest := takeScalarDest(node)
	if hasScalarDest {
		node = rest
	}
	if err := decodeScalarOr(node, glob, obj); err != nil {
		return err
	}
	switch {
	case !hasScalarDest:
	case isDestRule(scalarDest):
		*destRule = scalarDest
	default:
		*dest = []DestSpec{{Path: scalarDest}}
	}
	return nil
}

func isDestRule(dest string) bool {
	if len(dest) >= 2 && dest[0] == 's' && dest[1] != '\\' && !isWord(dest[1]) {
		return true
	}
	return strings.HasSuffix(dest, "/**")
}

func takeScalarDest(value *yaml.Node) (string, *yaml.Node, bool) {
	if value.Kind != yaml.MappingNode {
		return "", nil, false
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		if value.Content[i].Value != "dest" || value.Content[i+1].Kind != yaml.ScalarNode {
			continue
		}
		rule := value.Content[i+1].Value
		rest := *value
		rest.Content = slices.Concat(value.Content[:i], value.Content[i+2:])
		return rule, &rest, true
	}
	return "", nil, false
}

func DestRel(it FileItem) string {
	if len(it.Dests) > 0 {
		return it.Dests[0].Path
	}
	return it.Rel
}

func Load(path string, in Interp) (*Doc, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("spec not found: %s", path)
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	d := &Doc{}
	if len(doc.Content) == 0 {
		return d, nil
	}
	m := doc.Content[0]
	if m.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("parse %s: want a mapping at the top level", path)
	}
	it, err := newInterpolator(in, m)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	it.walkDoc(m)
	d.EnvUnset, d.EnvRefs, d.Lookup, d.Variables = it.unset, it.refs, it.lookup, it.vars
	if len(it.varUnset) > 0 {
		return nil, VarUnsetError(path, it.varUnset)
	}
	if in.Policy != envinterp.Policies.Empty && len(d.EnvUnset[topLevelProfile]) > 0 {
		return nil, EnvUnsetError(path, d.EnvUnset[topLevelProfile])
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		key, node := m.Content[i].Value, m.Content[i+1]
		if err := d.decodeKey(key, node); err != nil {
			return nil, err
		}
	}
	return d, nil
}

func (d *Doc) decodeKey(key string, node *yaml.Node) error {
	switch key {
	case "options":
		return node.Decode(&d.Options)
	case "env":
		return node.Decode(&d.Env)
	case "variables":
		return nil
	case "include":
		var inc struct {
			Sources []SpecSourceRecipe `yaml:"sources"`
		}
		if err := node.Decode(&inc); err != nil {
			return fmt.Errorf("parse include: %w", err)
		}
		d.Include = inc.Sources
		return nil
	default:
		var ps ProfileRecipe
		if err := node.Decode(&ps); err != nil {
			return fmt.Errorf("parse profile %q: %w", key, err)
		}
		if err := checkProfileType(key, ps.Type); err != nil {
			return err
		}
		ps.Include.Profiles = expandProfileRefs(ps.Include.Profiles)
		ps.Source.ProfileName = key
		d.ProfileRecipes = append(d.ProfileRecipes, ps)
		return nil
	}
}

var deprecationsSeen sync.Map

// [why] a spec loads more than once per run (source init, then discovery): one line per distinct
// deprecation keeps the warning readable
func warnDeprecated(msg string) {
	if _, seen := deprecationsSeen.LoadOrStore(msg, true); !seen {
		log.EmitWarn("load-spec", "deprecated", msg)
	}
}

// [why] a missing type warns, not errors: consumers pull upstream specs at pinned tags, so the
// requirement bites only once every upstream has re-tagged with a type on each profile
func checkProfileType(name string, t ProfileType) error {
	if t == "" {
		warnDeprecated(fmt.Sprintf("profile %q: type is missing, set type: %s (required in a coming release)", name, strings.Join(ProfileTypeNames, " | ")))
		return nil
	}
	if err := ValidateProfileType(string(t)); err != nil {
		return fmt.Errorf("profile %q: %w", name, err)
	}
	return nil
}

// [<] 🤖🤖
