package spec

// [>] 🤖🤖

import (
	"embed"
	"maps"
	"path/filepath"
	"slices"
	"testing"

	"gitlab.com/konradodwrot/go-modules/che/internal/testutil"
	"gitlab.com/konradodwrot/go-modules/lib/testyml"
)

//go:embed all:testdata
var td embed.FS

type permWant struct {
	Owner      string `yaml:"owner"`
	OwnerGroup string `yaml:"ownerGroup"`
	Chmod      string `yaml:"chmod"`
}

type optWant struct {
	WriteType               string `yaml:"writeType"`
	SkipAutoGeneratedHeader bool   `yaml:"skipAutoGeneratedHeader"`
	RenderReferencedFiles   bool   `yaml:"renderReferencedFiles"`
}

type pluginWant struct {
	URL     string            `yaml:"url"`
	Profile string            `yaml:"profile"`
	Env     map[string]string `yaml:"env"`
}

type wantSet struct {
	testyml.Want  `yaml:",inline"`
	Links         []string                     `yaml:"links"`
	Copies        []string                     `yaml:"copies"`
	Templates     []string                     `yaml:"templates"`
	Dirs          []string                     `yaml:"dirs"`
	ExtraDirs     []string                     `yaml:"extraDirs"`
	Scripts       []string                     `yaml:"scripts"`
	Services      []string                     `yaml:"services"`
	Perms         map[string]permWant          `yaml:"perms"`
	Dests         map[string][]string          `yaml:"dests"`
	Ctx           map[string]map[string]string `yaml:"ctx"`
	TemplateDests [][]string                   `yaml:"templateDests"`
	TemplateOpts  [][]optWant                  `yaml:"templateOpts"`
	Plugins       []pluginWant                 `yaml:"plugins"`
}

func rels(items []FileItem) []string {
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = it.Rel
	}
	return out
}

func dirPaths(items []FileItem) []string {
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = it.Dests[0].Path
	}
	return out
}

func destPaths(item FileItem) []string {
	out := make([]string, len(item.Dests))
	for i, d := range item.Dests {
		out[i] = d.Path
	}
	return out
}

func findItem(res Resolved, key string) *FileItem {
	for _, items := range [][]FileItem{res.Links, res.Copies, res.Templates} {
		if i := slices.IndexFunc(items, func(it FileItem) bool { return it.Rel == key }); i >= 0 {
			return &items[i]
		}
	}
	if i := slices.IndexFunc(res.ExtraDirs, func(it FileItem) bool { return it.Dests[0].Path == key }); i >= 0 {
		return &res.ExtraDirs[i]
	}
	return nil
}

func projections(res Resolved) map[string][]string {
	return map[string][]string{
		"links":     rels(res.Links),
		"copies":    rels(res.Copies),
		"templates": rels(res.Templates),
		"dirs":      res.Dirs,
		"extraDirs": dirPaths(res.ExtraDirs),
		"scripts":   res.Scripts,
		"services":  res.Services,
	}
}

func (w wantSet) lists() map[string][]string {
	return map[string][]string{
		"links":     w.Links,
		"copies":    w.Copies,
		"templates": w.Templates,
		"dirs":      w.Dirs,
		"extraDirs": w.ExtraDirs,
		"scripts":   w.Scripts,
		"services":  w.Services,
	}
}

func assertWant(t *testing.T, res Resolved, w wantSet) {
	t.Helper()
	got := projections(res)
	for key, want := range w.lists() {
		if want == nil {
			continue
		}
		if !slices.Equal(got[key], want) {
			t.Errorf("%s = %v, want %v", key, got[key], want)
		}
	}
	for key, p := range w.Perms {
		item := findItem(res, key)
		if item == nil {
			t.Errorf("perms: %q not resolved", key)
			continue
		}
		if (p.Owner != "" && item.Owner != p.Owner) ||
			(p.OwnerGroup != "" && item.OwnerGroup != p.OwnerGroup) ||
			(p.Chmod != "" && item.Chmod != p.Chmod) {
			t.Errorf("perms[%q] = %+v, want %+v", key, item.Perms, p)
		}
	}
	for key, want := range w.Dests {
		item := findItem(res, key)
		if item == nil {
			t.Errorf("dests: %q not resolved", key)
			continue
		}
		if got := destPaths(*item); !slices.Equal(got, want) {
			t.Errorf("dests[%q] = %v, want %v", key, got, want)
		}
	}
	for key, want := range w.Ctx {
		item := findItem(res, key)
		if item == nil {
			t.Errorf("ctx: %q not resolved", key)
			continue
		}
		if !maps.Equal(item.Ctx, want) {
			t.Errorf("ctx[%q] = %v, want %v", key, item.Ctx, want)
		}
	}
	for i, want := range w.TemplateDests {
		if i >= len(res.Templates) {
			t.Errorf("templateDests[%d]: only %d templates resolved", i, len(res.Templates))
			continue
		}
		if got := destPaths(res.Templates[i]); !slices.Equal(got, want) {
			t.Errorf("templateDests[%d] = %v, want %v", i, got, want)
		}
	}
	for i, opts := range w.TemplateOpts {
		if i >= len(res.Templates) {
			t.Errorf("templateOpts[%d]: only %d templates resolved", i, len(res.Templates))
			continue
		}
		dests := res.Templates[i].Dests
		if len(opts) != len(dests) {
			t.Errorf("templateOpts[%d]: %d dests, want %d", i, len(dests), len(opts))
			continue
		}
		for j, o := range opts {
			if string(dests[j].Options.WriteType) != o.WriteType || dests[j].Options.SkipAutoGeneratedHeader != o.SkipAutoGeneratedHeader || dests[j].Options.RenderReferencedFiles != o.RenderReferencedFiles {
				t.Errorf("templateOpts[%d][%d] = %+v, want %+v", i, j, dests[j].Options, o)
			}
		}
	}
	if w.Plugins != nil {
		if len(res.Plugins) != len(w.Plugins) {
			t.Fatalf("plugins = %v, want %v", res.Plugins, w.Plugins)
		}
		for i, p := range w.Plugins {
			got := res.Plugins[i]
			if got.URL != p.URL || got.Profile != p.Profile || !maps.Equal(got.Env, p.Env) {
				t.Errorf("plugins[%d] = %+v, want %+v", i, got, p)
			}
		}
	}
}

func assertMembership(t *testing.T, res Resolved, w *wantSet, present bool) {
	t.Helper()
	if w == nil {
		return
	}
	got := projections(res)
	for key, entries := range w.lists() {
		for _, e := range entries {
			if slices.Contains(got[key], e) != present {
				t.Errorf("%s: %q present=%v, want present=%v (%v)", key, e, !present, present, got[key])
			}
		}
	}
}

func TestResolve(t *testing.T) {
	type in struct {
		Spec     string
		Tree     string
		Profiles []string
	}
	type c struct {
		Name     string
		In       in
		Want     *wantSet
		Contains *wantSet
		NotWant  *wantSet `yaml:"notWant"`
	}
	testyml.Run(t, td, "testdata/spec/resolve.spec.yml", func(t *testing.T, c c) {
		dir := t.TempDir()
		testyml.CopyDir(t, td, "testdata/fixture/resolve/"+c.In.Tree, dir)
		if c.In.Spec != "" {
			testutil.WriteTree(t, dir, map[string]string{"che.yml": testutil.Spec(t, c.In.Spec)})
		}
		testutil.GitRepo(t, dir)
		s, err := Load(filepath.Join(dir, "che.yml"))
		if err != nil {
			t.Fatal(err)
		}
		res, err := s.Resolve(c.In.Profiles, filepath.Join(dir, "root"))
		if c.Want != nil && c.Want.IsErrorWanted() {
			c.Want.CheckErr(t, err)
			return
		}
		if err != nil {
			t.Fatal(err)
		}
		if c.Want != nil {
			assertWant(t, res, *c.Want)
		}
		assertMembership(t, res, c.Contains, true)
		assertMembership(t, res, c.NotWant, false)
	})
}

func TestEligibleProfiles(t *testing.T) {
	type in struct {
		Spec     string
		OS       string `yaml:"os"`
		Virt     bool
		ForceOne string `yaml:"forceOne"`
		ForceAll bool   `yaml:"forceAll"`
	}
	type want struct {
		Profiles []string
		Error    bool
	}
	type c struct {
		Name string
		In   in
		Want want
	}
	testyml.Run(t, td, "testdata/spec/eligible_profiles.spec.yml", func(t *testing.T, c c) {
		dir := t.TempDir()
		testutil.WriteTree(t, dir, map[string]string{"che.yml": testutil.Spec(t, c.In.Spec)})
		s, err := Load(filepath.Join(dir, "che.yml"))
		if err != nil {
			t.Fatal(err)
		}
		got, err := s.EligibleProfiles(c.In.ForceOne, c.In.ForceAll, stubEvaluator(c.In.OS, c.In.Virt).EvalExecIf)
		if c.Want.Error {
			if err == nil {
				t.Fatalf("EligibleProfiles = %v, want error", got)
			}
			return
		}
		if err != nil {
			t.Fatal(err)
		}
		if !slices.Equal(got, c.Want.Profiles) {
			t.Errorf("EligibleProfiles = %v, want %v", got, c.Want.Profiles)
		}
	})
}

// [<] 🤖🤖
