package spec

// [>] 🤖🤖

import (
	"embed"
	"maps"
	"path/filepath"
	"slices"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"gitlab.com/konradodwrot/go-modules/che/internal/testutil"
	"gitlab.com/konradodwrot/go-modules/lib/testyml"
)

//go:embed all:testdata
var td embed.FS

type permWant struct {
	Owner      string `yaml:"owner"`
	OwnerGroup string `yaml:"ownerGroup"`
	Chmod      string `yaml:"chmod"`
}

type optWant struct {
	WriteType               string `yaml:"writeType"`
	SkipAutoGeneratedHeader bool   `yaml:"skipAutoGeneratedHeader"`
	RenderReferencedFiles   bool   `yaml:"renderReferencedFiles"`
}

type pluginWant struct {
	URL     string            `yaml:"url"`
	Profile string            `yaml:"profile"`
	Env     map[string]string `yaml:"env"`
}

// wantSet is resolve's domain projection set, carried inside
// expected/notExpected/contains (the canonical schema's one exception).
type wantSet struct {
	testyml.Expected[struct{}] `yaml:",inline"`

	Links         []string                     `yaml:"links"`
	Copies        []string                     `yaml:"copies"`
	Templates     []string                     `yaml:"templates"`
	Dirs          []string                     `yaml:"dirs"`
	ExtraDirs     []string                     `yaml:"extraDirs"`
	Scripts       []string                     `yaml:"scripts"`
	Services      []string                     `yaml:"services"`
	Perms         map[string]permWant          `yaml:"perms"`
	Dests         map[string][]string          `yaml:"dests"`
	Ctx           map[string]map[string]string `yaml:"ctx"`
	TemplateDests [][]string                   `yaml:"templateDests"`
	TemplateOpts  [][]optWant                  `yaml:"templateOpts"`
	Plugins       []pluginWant                 `yaml:"plugins"`
}

// resolveCase is resolve's spec case: the canonical shape plus contains.
type resolveCase struct {
	Name        string          `yaml:"name"`
	Context     testyml.Context `yaml:"context"`
	Input       testyml.Input   `yaml:"input"`
	Expected    *wantSet        `yaml:"expected"`
	NotExpected *wantSet        `yaml:"notExpected"`
	Contains    *wantSet        `yaml:"contains"`
}

func rels(items []FileItem) []string {
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = it.Rel
	}
	return out
}

func dirPaths(items []FileItem) []string {
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = it.Dests[0].Path
	}
	return out
}

func destPaths(item FileItem) []string {
	out := make([]string, len(item.Dests))
	for i, d := range item.Dests {
		out[i] = d.Path
	}
	return out
}

func findItem(res Resolved, key string) *FileItem {
	for _, items := range [][]FileItem{res.Links, res.Copies, res.Templates} {
		if i := slices.IndexFunc(items, func(it FileItem) bool { return it.Rel == key }); i >= 0 {
			return &items[i]
		}
	}
	if i := slices.IndexFunc(res.ExtraDirs, func(it FileItem) bool { return it.Dests[0].Path == key }); i >= 0 {
		return &res.ExtraDirs[i]
	}
	return nil
}

func projections(res Resolved) map[string][]string {
	return map[string][]string{
		"links":     rels(res.Links),
		"copies":    rels(res.Copies),
		"templates": rels(res.Templates),
		"dirs":      res.Dirs,
		"extraDirs": dirPaths(res.ExtraDirs),
		"scripts":   res.Scripts,
		"services":  res.Services,
	}
}

func (w wantSet) lists() map[string][]string {
	return map[string][]string{
		"links":     w.Links,
		"copies":    w.Copies,
		"templates": w.Templates,
		"dirs":      w.Dirs,
		"extraDirs": w.ExtraDirs,
		"scripts":   w.Scripts,
		"services":  w.Services,
	}
}

func assertWant(t *testing.T, res Resolved, w wantSet) {
	t.Helper()
	got := projections(res)
	for key, want := range w.lists() {
		if want != nil {
			assert.Equal(t, want, got[key], key)
		}
	}
	for key, p := range w.Perms {
		item := findItem(res, key)
		if !assert.NotNil(t, item, "perms: %q not resolved", key) {
			continue
		}
		if (p.Owner != "" && item.Owner != p.Owner) ||
			(p.OwnerGroup != "" && item.OwnerGroup != p.OwnerGroup) ||
			(p.Chmod != "" && item.Chmod != p.Chmod) {
			t.Errorf("perms[%q] = %+v, want %+v", key, item.Perms, p)
		}
	}
	for key, want := range w.Dests {
		item := findItem(res, key)
		if !assert.NotNil(t, item, "dests: %q not resolved", key) {
			continue
		}
		got := destPaths(*item)
		if len(want) == 0 {
			assert.Empty(t, got, "dests[%q]", key)
			continue
		}
		assert.Equal(t, want, got, "dests[%q]", key)
	}
	for key, want := range w.Ctx {
		item := findItem(res, key)
		if !assert.NotNil(t, item, "ctx: %q not resolved", key) {
			continue
		}
		assert.True(t, maps.Equal(item.Ctx, want), "ctx[%q] = %v, want %v", key, item.Ctx, want)
	}
	for i, want := range w.TemplateDests {
		if !assert.Less(t, i, len(res.Templates), "templateDests[%d]: only %d templates resolved", i, len(res.Templates)) {
			continue
		}
		assert.Equal(t, want, destPaths(res.Templates[i]), "templateDests[%d]", i)
	}
	for i, opts := range w.TemplateOpts {
		if !assert.Less(t, i, len(res.Templates), "templateOpts[%d]: only %d templates resolved", i, len(res.Templates)) {
			continue
		}
		dests := res.Templates[i].Dests
		if !assert.Len(t, dests, len(opts), "templateOpts[%d]", i) {
			continue
		}
		for j, o := range opts {
			got := optWant{
				WriteType:               dests[j].Options.WriteType,
				SkipAutoGeneratedHeader: dests[j].Options.SkipAutoGeneratedHeader,
				RenderReferencedFiles:   dests[j].Options.RenderReferencedFiles,
			}
			assert.Equal(t, o, got, "templateOpts[%d][%d]", i, j)
		}
	}
	if w.Plugins != nil {
		require.Len(t, res.Plugins, len(w.Plugins))
		for i, p := range w.Plugins {
			got := res.Plugins[i]
			if got.URL != p.URL || got.Profile != p.Profile || !maps.Equal(got.Env, p.Env) {
				t.Errorf("plugins[%d] = %+v, want %+v", i, got, p)
			}
		}
	}
}

func assertMembership(t *testing.T, res Resolved, w *wantSet, present bool) {
	t.Helper()
	if w == nil {
		return
	}
	got := projections(res)
	for key, entries := range w.lists() {
		for _, e := range entries {
			assert.Equal(t, present, slices.Contains(got[key], e), "%s: %q (%v)", key, e, got[key])
		}
	}
}

func TestResolve(t *testing.T) {
	testyml.Run(t, td, "testdata/spec/resolve.test.spec.yml", func(t *testing.T, c resolveCase) {
		dir := t.TempDir()
		testyml.CopyDir(t, td, c.Context.Pwd, dir)
		if name := c.Input.Args.String(t, 0); name != "" {
			testutil.WriteTree(t, dir, map[string]string{"che.yml": testutil.Spec(t, name)})
		}
		testutil.GitRepo(t, dir)
		s, err := Load(filepath.Join(dir, "che.yml"))
		require.NoError(t, err)
		res, err := s.Resolve(c.Input.Args.Strings(t, 1), filepath.Join(dir, "root"))
		if c.Expected != nil && c.Expected.Check(t, err) {
			return
		}
		require.NoError(t, err)
		if c.Expected != nil {
			assertWant(t, res, *c.Expected)
		}
		assertMembership(t, res, c.Contains, true)
		assertMembership(t, res, c.NotExpected, false)
	})
}

func TestEligibleProfiles(t *testing.T) {
	testyml.Eq(t, td, "testdata/spec/eligible_profiles.test.spec.yml", func(t *testing.T, c testyml.Case[[]string]) ([]string, error) {
		a := c.Input.Args
		dir := testutil.Tree(t, map[string]string{"che.yml": testutil.Spec(t, a.String(t, 0))})
		s, err := Load(filepath.Join(dir, "che.yml"))
		require.NoError(t, err)
		return s.EligibleProfiles(a.String(t, 3), a.Bool(t, 4), stubEvaluator(a.String(t, 1), a.Bool(t, 2)).EvalExecIf)
	})
}

// [<] 🤖🤖
