##[>] 🤖🤖
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - release

variables:
  GOMODCACHE: $CI_PROJECT_DIR/.cache/go-mod
  GOCACHE: $CI_PROJECT_DIR/.cache/go-build
  CC: clang

test:
  image: golang:1.26-bookworm
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    - key:
        files:
          - go.sum
      paths:
        - .cache/go-mod
        - .cache/go-build
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends clang make
  script:
    - make test

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    BRANCH: $CI_COMMIT_BRANCH
    REF: $CI_COMMIT_SHA
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
  before_script:
    - apk add --no-cache make zsh
  script:
    - make create-tag

prerelease:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: [test]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    BRANCH: $CI_COMMIT_REF_NAME
    REF: $CI_COMMIT_SHA
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
  before_script:
    - apk add --no-cache make zsh
  script:
    - make create-tag
##[<] 🤖🤖
