##[>] 🤖🤖
version: 2

project_name: che

dist: darwin-dist

snapshot:
  version_template: '{{ envOrDefault "MODULE_VERSION" "0.0.0-local" }}'

builds:
  - id: che-darwin
    main: .
    binary: che
    goos: [darwin]
    goarch: [arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X gitlab.com/konradodwrot/go-modules/che/internal/cli.version={{.Version}}
    env:
      - CGO_ENABLED=0

archives:
  - id: che
    ids: [che-darwin]
    formats: [tar.gz]
    name_template: 'che_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
  disable: true
##[<] 🤖🤖
