##[>] 🤖🤖
site_name: che
site_url: https://konradodwrot.gitlab.io/go/che/
repo_url: https://gitlab.com/konradodwrot/go/che
repo_name: konradodwrot/go/che
use_directory_urls: !ENV [DOCS_DIR_URLS, true]

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: light mode

nav:
  - Overview: index.md
  - che.yml Schema: spec.md
  - CLI Reference: cli.md
  - License: license.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
##[<] 🤖🤖
