##[>] 🤖🤖
che-install-test-che:
  stage: verify
  needs: []
  parallel:
    matrix:
      - ARCH: [amd64, arm64]
  tags:
    - gke-linux-$ARCH-small
  image:
    name: $ARTIFACT_REGISTRY_PROXY_DOCKERHUB/library/alpine:3
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: [che/che-install.sh, ci/che-install-test.sh, ci/che-install-changed.sh, ci/che-install.gitlab-ci.yml]
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: [che/che-install.sh, ci/che-install-test.sh, ci/che-install-changed.sh, ci/che-install.gitlab-ci.yml]
  variables:
    LATEST_FALLBACK: "1"
  script:
    - sh ci/che-install-test.sh
##[<] 🤖🤖
