#!/usr/bin/env zsh
##[>] 🤖🤖
# Mint and publish a release for each schema whose generated bytes changed.
# Args: $1 ref/SHA to tag (default: HEAD).
#
# Runs before the che release job and takes che's next tag as CHE_MIN_VERSION,
# computed once by that job's own next-tag.zsh. Recomputing it here would let a
# tag landing in between make the -che-min floor name a release other than the
# one actually cut.
#
# Writes CHE_SCHEMA_REF, CHE_PACKAGES_SCHEMA_REF and CHE_VARIABLES_SCHEMA_REF to $SCHEMA_VERSIONS_ENV as a
# dotenv artifact, always: an unchanged schema reports the version already
# published, so a consumer reading the dotenv sees the shipped version either way.
set -eu

REF="${1:-$(git rev-parse HEAD)}"
CHE_MIN_VERSION="${CHE_MIN_VERSION:?che version the floor names}"
OUT="${SCHEMA_VERSIONS_ENV:-schema-versions.env}"

ROOT=$(git rev-parse --show-toplevel)
: > "$OUT"

for schema in che che-packages che-variables; do
  NAME="${schema}-schema"
  VAR="${${schema:u}//-/_}_SCHEMA_REF"

  set +e
  VERSION=$("$ROOT/ci/schema-version.zsh" "$schema" "$CHE_MIN_VERSION")
  STATUS=$?
  set -e

  if (( STATUS > 1 )) {
    print -u2 "release-schemas: ${NAME} version check failed (${STATUS})"
    exit "$STATUS"
  }

  print -r -- "${VAR}=${VERSION}" >> "$OUT"

  if (( STATUS == 1 )) {
    print "${NAME}: unchanged, staying at ${VERSION}"
    continue
  }

  print "${NAME}: minting ${VERSION} at ${REF}"
  glab release create "${NAME}/${VERSION}" \
    --name "${NAME} ${VERSION}" \
    --ref "$REF" \
    --notes "${NAME} ${VERSION}"$'\n\n'"Generated from che's Go models. Minimum che release understanding this vocabulary: ${CHE_MIN_VERSION}."

  "$ROOT/ci/publish-schema.zsh" "$schema" "$VERSION"
done

print "schema versions:"
cat "$OUT"
##[<] 🤖🤖
