##[>] 🤖🤖
version: 2

project_name: render-files

dist: darwin-dist

before:
  hooks:
    - go mod tidy

builds:
  - id: render-dirs-tree-darwin
    main: ./cmd/render-dirs-tree
    binary: render-dirs-tree
    goos: [darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CC=cc
      - CXX=c++

  - id: render-makefile-doc-darwin
    main: ./cmd/render-makefile-doc
    binary: render-makefile-doc
    goos: [darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CC=cc
      - CXX=c++

  - id: render-tpl-darwin
    main: ./cmd/render-tpl
    binary: render-tpl
    goos: [darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CC=cc
      - CXX=c++

  - id: render-repo-group-index-darwin
    main: ./cmd/render-repo-group-index
    binary: render-repo-group-index
    goos: [darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CC=cc
      - CXX=c++

archives:
  - id: render-dirs-tree
    ids: [render-dirs-tree-darwin]
    formats: [tar.gz]
    name_template: 'render-dirs-tree_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: render-makefile-doc
    ids: [render-makefile-doc-darwin]
    formats: [tar.gz]
    name_template: 'render-makefile-doc_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: render-tpl
    ids: [render-tpl-darwin]
    formats: [tar.gz]
    name_template: 'render-tpl_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: render-repo-group-index
    ids: [render-repo-group-index-darwin]
    formats: [tar.gz]
    name_template: 'render-repo-group-index_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
  disable: true
##[<] 🤖🤖
